apiVersion: v1
kind: Secret
metadata:
  name: connector-db-secret
  labels:
    app: edc-connector
    component: connector-db
type: Opaque
stringData:
  # PostgreSQL database credentials for connector
  POSTGRES_USER: "{{ secrets.connector_db.postgres_user }}"
  POSTGRES_PASSWORD: "{{ secrets.connector_db.postgres_password }}"
  POSTGRES_DB: "{{ secrets.connector_db.postgres_db }}"
