apiVersion: v1
kind: Secret
metadata:
  name: connector-secret
  labels:
    app: edc-connector
    component: connector
type: Opaque
stringData:
  # Database connection (connector DB)
  EDC_DATASOURCE_DEFAULT_URL: "{{ secrets.connector.datasource_default_url }}"
  EDC_DATASOURCE_DEFAULT_USER: "{{ secrets.connector.datasource_default_user }}"
  EDC_DATASOURCE_DEFAULT_PASSWORD: "{{ secrets.connector.datasource_default_password }}"
  EDC_DATASOURCE_DEFAULT_NAME: "default"

  # Connector secrets
  EDC_VAULT_HASHICORP_TOKEN: "{{ secrets.connector.vault_hashicorp_token }}"
  WEB_HTTP_AUTH_KEY: "{{ secrets.connector.web_http_auth_key }}"
  WEB_HTTP_MANAGEMENT_AUTH_KEY: "{{ secrets.connector.web_http_management_auth_key }}"
  WEB_HTTP_CONTROL_AUTH_KEY: "{{ secrets.connector.web_http_control_auth_key }}"
  WEB_HTTP_CATALOGPROXY_AUTH_KEY: "{{ secrets.connector.web_http_catalogproxy_auth_key }}"
