apiVersion: v1
kind: Secret
metadata:
  name: connector-secret
  labels:
    app: edc-connector
    component: connector
type: Opaque
stringData:
  # Database connection (connector DB)
  EDC_DATASOURCE_DEFAULT_URL: "{{ secrets.connector.datasource_default_url }}"
  EDC_DATASOURCE_DEFAULT_USER: "{{ secrets.connector.datasource_default_user }}"
  EDC_DATASOURCE_DEFAULT_PASSWORD: "{{ secrets.connector.datasource_default_password }}"

  # Connector secrets
  EDC_IAM_STS_OAUTH_CLIENT_SECRET: "{{ secrets.connector.iam_sts_oauth_client_secret }}"
  EDC_VAULT_HASHICORP_TOKEN: "{{ secrets.connector.vault_hashicorp_token }}"
  EDC_API_AUTH_KEY: "{{ secrets.connector.api_auth_key }}"
