apiVersion: v1
kind: Secret
metadata:
  name: consumer-backend-secret
  labels:
    app: edc-consumer
    component: consumer-backend
type: Opaque
stringData:
  # S3 / RustFS credentials
  S3_ACCESS_KEY: "{{ secrets.consumer_backend.s3_access_key }}"
  S3_SECRET_KEY: "{{ secrets.consumer_backend.s3_secret_key }}"
