apiVersion: v1
kind: Secret
metadata:
  name: identity-hub-secret
  labels:
    app: edc-connector
    component: identity-hub
type: Opaque
stringData:
  # Identity Hub secrets
  EDC_VAULT_HASHICORP_TOKEN: "{{ secrets.identity_hub.vault_hashicorp_token }}"
  EDC_IH_API_SUPERUSER_KEY: "{{ secrets.identity_hub.ih_api_superuser_key }}"
  EDC_DATASOURCE_DEFAULT_URL: "{{ secrets.identity_hub.datasource_default_url }}"
  EDC_DATASOURCE_DEFAULT_USER: "{{ secrets.identity_hub.datasource_default_user }}"
  EDC_DATASOURCE_DEFAULT_PASSWORD: "{{ secrets.identity_hub.datasource_default_password }}"
