apiVersion: v1
kind: Secret
metadata:
  name: identity-hub-db-secret
  labels:
    app: edc-connector
    component: identity-hub-db
type: Opaque
stringData:
  # PostgreSQL database credentials for identity-hub
  POSTGRES_USER: "{{ secrets.identity_hub_db.postgres_user }}"
  POSTGRES_PASSWORD: "{{ secrets.identity_hub_db.postgres_password }}"
  POSTGRES_DB: "{{ secrets.identity_hub_db.postgres_db }}"
