apiVersion: v1
kind: Secret
metadata:
  name: keycloak-secret
  labels:
    app: edc-connector
    component: keycloak
type: Opaque
stringData:
  # Keycloak admin credentials
  KEYCLOAK_ADMIN: "{{ secrets.keycloak.admin }}"
  KEYCLOAK_ADMIN_PASSWORD: "{{ secrets.keycloak.admin_password }}"
  
  # Database connection (keycloak DB)
  KC_DB_URL_DATABASE: "{{ secrets.keycloak.db }}"
  KC_DB_SCHEMA: "{{ secrets.keycloak.db_schema }}"
  KC_DB_URL_HOST: "{{ secrets.keycloak.db_url }}"
  KC_DB_USERNAME: "{{ secrets.keycloak.db_username }}"
  KC_DB_PASSWORD: "{{ secrets.keycloak.db_password }}"
