apiVersion: v1
kind: Secret
metadata:
  name: keycloak-db-secret
  labels:
    app: edc-connector
    component: keycloak-db
type: Opaque
stringData:
  # PostgreSQL database credentials for keycloak
  POSTGRES_USER: "{{ secrets.keycloak_db.postgres_user }}"
  POSTGRES_PASSWORD: "{{ secrets.keycloak_db.postgres_password }}"
  POSTGRES_DB: "{{ secrets.keycloak_db.postgres_db }}"
