[metadata]
format.version = "1.1"

[versions]
awaitility = "4.3.0"
edc = "0.14.0"
edc-build = "1.0.0"
jackson = "2.18.2"
jakarta-json = "2.1.3"
jakartaRs = "3.1.0"
parsson = "1.1.6"
postgres = "42.7.3"
restAssured = "5.5.6"
shared-extensions = "1.0.0"

[libraries]
# PSNC libs
psnc-auth-composite = { module = "com.psnc.mvds:auth-composite", version.ref = "shared-extensions" }
psnc-vault-keys-seeder = { module = "com.psnc.mvds:vault-keys-seeder", version.ref = "shared-extensions" }

# EDC libs
# standard
edc-configuration-filesystem = { module = "org.eclipse.edc:configuration-filesystem", version.ref = "edc" }

# identityhub SPI modules
edc-ih-spi-did = { module = "org.eclipse.edc:did-spi", version.ref = "edc" }
edc-ih-spi-credentials = { module = "org.eclipse.edc:verifiable-credential-spi", version.ref = "edc" }
edc-ih-spi = { module = "org.eclipse.edc:identity-hub-spi", version.ref = "edc" }

edc-spi-identity-did = { module = "org.eclipse.edc:identity-did-spi", version.ref = "edc" }
edc-spi-web = { module = "org.eclipse.edc:web-spi", version.ref = "edc" }
jakarta-rsApi = { module = "jakarta.ws.rs:jakarta.ws.rs-api", version.ref = "jakartaRs" }

# BOM modules
edc-bom-identityhub = { module = "org.eclipse.edc:identityhub-bom", version.ref = "edc" }

# did-example-resolver
edc-did-core = { module = "org.eclipse.edc:identity-did-core", version.ref = "edc" }

# persistence
edc-bom-identityhub-sql = { module = "org.eclipse.edc:identityhub-feature-sql-bom", version.ref = "edc" }
edc-vault-hashicorp = { module = "org.eclipse.edc:vault-hashicorp", version.ref = "edc" }

[plugins]
shadow = { id = "com.gradleup.shadow", version = "8.3.6" }
edc-build = { id = "org.eclipse.edc.edc-build", version.ref = "edc-build" }
