#consumer
connectorconsumer_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"

identityhubconsumer_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"

consumerdashboard_resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1"
    memory: "400Mi"

consback_resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1"
    memory: "400Mi"

minio_resources:
  requests:
    cpu: "1000m"
    memory: "300Mi"
  limits:
    cpu: "1500m"
    memory: "1Gi"

identityproviderconsumer_resources:
  requests:
    cpu: "100m"
    memory: "400Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

#provider
connectorprovider_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"

identityhubprovider_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"

identityproviderprovider_resources:
  requests:
    cpu: "100m"
    memory: "400Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

providerdashboard_resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1"
    memory: "400Mi"

#authority
federatedcatalog_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"

dataspaceportal_resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1"
    memory: "400Mi"

dataspacehub_resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1"
    memory: "400Mi"

mailservice_resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1"
    memory: "400Mi"

identityhubfederatedcatalog_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"