# Service adresses
consumer_connector_address: "https://consumer-connector-dcp-data-space.apps.bst2.paas.psnc.pl"
consumer_identity_hub_address: "https://consumer-identity-hub-dcp-data-space.apps.bst2.paas.psnc.pl"
consumer_dashboard_address: "https://consumer-dashboard-dcp-data-space.apps.bst2.paas.psnc.pl"
consumer_dashboard_address_shorten: "consumer-dashboard-dcp-data-space.apps.bst2.paas.psnc.pl"
consumer_keyvault_address: "https://consumer-keyvault-dcp-data-space.apps.bst2.paas.psnc.pl"
consumer_keycloak_address: "https://consumer-keycloak-dcp-data-space.apps.bst2.paas.psnc.pl"
consumer_keycloak_hostname: "consumer-keycloak-dcp-data-space.apps.bst2.paas.psnc.pl"
consumer_backend_address: "https://consumer-backend-dcp-data-space.apps.bst2.paas.psnc.pl"

provider_connector_address: "https://provider-connector-dcp-data-space.apps.bst2.paas.psnc.pl"
provider_identity_hub_address: "https://provider-identity-hub-dcp-data-space.apps.bst2.paas.psnc.pl"
provider_dashboard_address: "https://provider-dashboard-dcp-data-space.apps.bst2.paas.psnc.pl"
provider_dashboard_address_shorten: "provider-dashboard-dcp-data-space.apps.bst2.paas.psnc.pl"
provider_keyvault_address: "https://provider-keyvault-dcp-data-space.apps.bst2.paas.psnc.pl"
provider_keycloak_address: "https://provider-keycloak-dcp-data-space.apps.bst2.paas.psnc.pl"
provider_keycloak_hostname: "provider-keycloak-dcp-data-space.apps.bst2.paas.psnc.pl"

federated_catalog_address: "https://federated-catalog-dcp-data-space.apps.bst2.paas.psnc.pl"
federated_catalog_identity_hub_address: "https://federated-catalog-identity-hub-dcp-data-space.apps.bst2.paas.psnc.pl"
federated_catalog_keyvault_address: "https://federated-catalog-keyvault-dcp-data-space.apps.bst2.paas.psnc.pl"
data_space_portal_address: "https://data-space-portal-dcp-data-space.apps.bst2.paas.psnc.pl"
data_space_portal_address_shorten: "data-space-portal-dcp-data-space.apps.bst2.paas.psnc.pl"
data_space_hub_address: "https://data-space-hub-dcp-data-space.apps.bst2.paas.psnc.pl"
data_space_hub_keyvault_address: "https://data-space-hub-keyvault-dcp-data-space.apps.bst2.paas.psnc.pl"
mail_service_address: "https://mail-service-dcp-data-space.apps.bst2.paas.psnc.pl"

routes:
  # consumer connector
  - name: consumer-connector-api
    host: "{{ consumer_connector_address | regex_replace('^https?://', '') }}"
    path: "/api"
    service: "{{ application }}-connectorconsumer"
    target_port: api

  - name: consumer-connector-management
    host: "{{ consumer_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/management"
    service: "{{ application }}-connectorconsumer"
    target_port: management

  - name: consumer-connector-dsp
    host: "{{ consumer_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/dsp"
    service: "{{ application }}-connectorconsumer"
    target_port: dsp

  - name: consumer-connector-control
    host: "{{ consumer_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/control"
    service: "{{ application }}-connectorconsumer"
    target_port: control

  - name: consumer-connector-catalog
    host: "{{ consumer_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/catalog"
    service: "{{ application }}-connectorconsumer"
    target_port: catalog

  - name: consumer-connector-version
    host: "{{ consumer_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/version"
    service: "{{ application }}-connectorconsumer"
    target_port: version

  - name: consumer-connector-catalogproxy
    host: "{{ consumer_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/catalog-proxy"
    service: "{{ application }}-connectorconsumer"
    target_port: catalogproxy

  - name: consumer-connector-public
    host: "{{ consumer_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/public"
    service: "{{ application }}-connectorconsumer"
    target_port: public

  # consumer dashboard
  - name: consumer-dashboard
    host: "{{ consumer_dashboard_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-consumerdashboard"
    target_port: www

  # consumer ih
  - name: consumer-identity-hub-api
    host: "{{ consumer_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api"
    service: "{{ application }}-identityhubconsumer"
    target_port: api

  - name: consumer-identity-hub-credentials
    host: "{{ consumer_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api/credentials"
    service: "{{ application }}-identityhubconsumer"
    target_port: credentials

  - name: consumer-identity-hub-identity
    host: "{{ consumer_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api/identity"
    service: "{{ application }}-identityhubconsumer"
    target_port: identity

  - name: consumer-identity-hub-did
    host: "{{ consumer_identity_hub_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-identityhubconsumer"
    target_port: did

  - name: consumer-identity-hub-version
    host: "{{ consumer_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api/version"
    service: "{{ application }}-identityhubconsumer"
    target_port: version

  - name: consumer-identity-hub-sts
    host: "{{ consumer_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api/sts"
    service: "{{ application }}-identityhubconsumer"
    target_port: sts

  # consumer kv
  - name: consumer-key-vault
    host: "{{ consumer_keyvault_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-vault-keyvaultconsumer"
    target_port: vault-http

  # consumer keycloak
  - name: consumer-keycloak
    host: "{{ consumer_keycloak_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-identityproviderconsumer"
    target_port: keycloak-http

  # consumer minio
  - name: consumer-minio
    host: "{{ minio_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-minio"
    target_port: minio-http

  # consumer backend
  - name: consumer-backend
    host: "{{ consumer_backend_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-consback"
    target_port: receiver

  # provider connector
  - name: provider-connector-api
    host: "{{ provider_connector_address | regex_replace('^https?://', '') }}"
    path: "/api"
    service: "{{ application }}-connectorprovider"
    target_port: api

  - name: provider-connector-management
    host: "{{ provider_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/management"
    service: "{{ application }}-connectorprovider"
    target_port: management

  - name: provider-connector-dsp
    host: "{{ provider_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/dsp"
    service: "{{ application }}-connectorprovider"
    target_port: dsp

  - name: provider-connector-control
    host: "{{ provider_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/control"
    service: "{{ application }}-connectorprovider"
    target_port: control

  - name: provider-connector-catalog
    host: "{{ provider_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/catalog"
    service: "{{ application }}-connectorprovider"
    target_port: catalog

  - name: provider-connector-version
    host: "{{ provider_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/version"
    service: "{{ application }}-connectorprovider"
    target_port: version

  - name: provider-connector-catalogproxy
    host: "{{ provider_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/catalog-proxy"
    service: "{{ application }}-connectorprovider"
    target_port: catalogproxy

  - name: provider-connector-public
    host: "{{ provider_connector_address | regex_replace('^https?://', '') }}"
    path: "/api/public"
    service: "{{ application }}-connectorprovider"
    target_port: public

  # provider dashboard
  - name: provider-dashboard
    host: "{{ provider_dashboard_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-providerdashboard"
    target_port: www

  # provider ih
  - name: provider-identity-hub-api
    host: "{{ provider_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api"
    service: "{{ application }}-identityhubprovider"
    target_port: api

  - name: provider-identity-hub-credentials
    host: "{{ provider_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api/credentials"
    service: "{{ application }}-identityhubprovider"
    target_port: credentials

  - name: provider-identity-hub-identity
    host: "{{ provider_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api/identity"
    service: "{{ application }}-identityhubprovider"
    target_port: identity

  - name: provider-identity-hub-did
    host: "{{ provider_identity_hub_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-identityhubprovider"
    target_port: did

  - name: provider-identity-hub-version
    host: "{{ provider_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api/version"
    service: "{{ application }}-identityhubprovider"
    target_port: version

  - name: provider-identity-hub-sts
    host: "{{ provider_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api/sts"
    service: "{{ application }}-identityhubprovider"
    target_port: sts

  # provider kv
  - name: provider-key-vault
    host: "{{ provider_keyvault_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-vault-keyvaultprovider"
    target_port: vault-http

  # provider keycloak
  - name: provider-keycloak
    host: "{{ provider_keycloak_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-identityproviderprovider"
    target_port: keycloak-http

  # federated catalog
  - name: federated-catalog-api
    host: "{{ federated_catalog_address | regex_replace('^https?://', '') }}"
    path: "/api"
    service: "{{ application }}-federatedcatalog"
    target_port: api

  - name: federated-catalog-management
    host: "{{ federated_catalog_address | regex_replace('^https?://', '') }}"
    path: "/api/management"
    service: "{{ application }}-federatedcatalog"
    target_port: management

  - name: federated-catalog-dsp
    host: "{{ federated_catalog_address | regex_replace('^https?://', '') }}"
    path: "/api/dsp"
    service: "{{ application }}-federatedcatalog"
    target_port: dsp

  - name: federated-catalog-control
    host: "{{ federated_catalog_address | regex_replace('^https?://', '') }}"
    path: "/api/control"
    service: "{{ application }}-federatedcatalog"
    target_port: control

  - name: federated-catalog-catalog
    host: "{{ federated_catalog_address | regex_replace('^https?://', '') }}"
    path: "/api/catalog"
    service: "{{ application }}-federatedcatalog"
    target_port: catalog

  - name: federated-catalog-version
    host: "{{ federated_catalog_address | regex_replace('^https?://', '') }}"
    path: "/api/version"
    service: "{{ application }}-federatedcatalog"
    target_port: version

  - name: federated-catalog-targets
    host: "{{ federated_catalog_address | regex_replace('^https?://', '') }}"
    path: "/api/targets"
    service: "{{ application }}-federatedcatalog"
    target_port: targets

  - name: federated-catalog-public
    host: "{{ federated_catalog_address | regex_replace('^https?://', '') }}"
    path: "/api/public"
    service: "{{ application }}-federatedcatalog"
    target_port: public

  # federated catalog identity hub
  - name: federated-catalog-identity-hub-api
    host: "{{ federated_catalog_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api"
    service: "{{ application }}-identityhubfederatedcatalog"
    target_port: api

  - name: federated-catalog-identity-hub-credentials
    host: "{{ federated_catalog_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api/credentials"
    service: "{{ application }}-identityhubfederatedcatalog"
    target_port: credentials

  - name: federated-catalog-identity-hub-identity
    host: "{{ federated_catalog_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api/identity"
    service: "{{ application }}-identityhubfederatedcatalog"
    target_port: identity

  - name: federated-catalog-identity-hub-did
    host: "{{ federated_catalog_identity_hub_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-identityhubfederatedcatalog"
    target_port: did

  - name: federated-catalog-identity-hub-version
    host: "{{ federated_catalog_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api/version"
    service: "{{ application }}-identityhubfederatedcatalog"
    target_port: version

  - name: federated-catalog-identity-hub-sts
    host: "{{ federated_catalog_identity_hub_address | regex_replace('^https?://', '') }}"
    path: "/api/sts"
    service: "{{ application }}-identityhubfederatedcatalog"
    target_port: sts

  # federated catalog identity hub kv
  - name: federated-catalog-keyvault
    host: "{{ federated_catalog_keyvault_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-vault-keyvaultfederatedcatalog"
    target_port: vault-http

  - name: data-space-hub
    host: "{{ data_space_hub_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-dataspacehub"
    target_port: receiver
  
  # data space hub kv
  - name: data-space-hub-keyvault
    host: "{{ data_space_hub_keyvault_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-vault-keyvaultdataspacehub"
    target_port: vault-http

  - name: data-space-portal
    host: "{{ data_space_portal_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-dataspaceportal"
    target_port: www

  # mail service
  - name: mail-service
    host: "{{ mail_service_address | regex_replace('^https?://', '') }}"
    service: "{{ application }}-mailservice"
    target_port: receiver
