consumer_dashboard_app_config_obj:
  managementApiUrl: "{{ consumer_connector_address }}/api/management"
  catalogUrl: "{{ federated_catalog_address }}/api/catalog"
  theme: "theme-4"
  deploymentMode: "production"
  backendUrl: "{{ consumer_backend_address }}/edr-endpoint"
  edcApiKey: "edc"

provider_dashboard_app_config_obj:
  managementApiUrl: "{{ provider_connector_address }}/api/management"
  catalogUrl: "{{ federated_catalog_address }}/api/catalog"
  theme: "theme-3"
  deploymentMode: "production"
  backendUrl: "{{ consumer_backend_address }}/edr-endpoint"
  edcApiKey: "edc"

dataspaceportal_app_config_obj:
  apiBaseUrl: "{{ data_space_hub_address }}/api"
  isProduction: true