default:
  image: registry.paas.psnc.pl/devlab/gitlab-runner:v1

variables:
  GIT_STRATEGY: clone

stages:
  - build
  - test
  - upload
  - update_inventory

Build images:
  stage: build
  variables:
    ULIMIT_NOFILE: "16384:16384"
  script:
    - devlab_build_images

Upload images:
  stage: upload
  script:
    - devlab_push_images

Upload images to public DockerHub:
  stage: upload
  script:
    - apt update
    - apt install -y curl jq
    - cd ${CI_PROJECT_DIR}/docker
    - ./push-images-public.sh
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_BRANCH == "develop"'

Update inventory for main project:
  stage: update_inventory
  variables:
    inventory_repository_name: inventory
    inventory_hostname: $inventory_hostname_psnc
    gitlab_push_token: $gitlab_push_token_dev
  script:
    - devlab_update_inventory
  only:
    variables:
      - $CI_COMMIT_BRANCH == $branch_allowed_to_update_inventory

Update inventory for atos-psnc integration:
  stage: update_inventory
  variables:
    inventory_repository_name: atos-integration-inventory
    inventory_hostname: $inventory_hostname_psnc_atos
    gitlab_push_token: $gitlab_push_token_psnc_atos
  script:
    - devlab_update_inventory
  only:
    variables:
      - $CI_COMMIT_BRANCH == $branch_allowed_to_update_inventory_atos_psnc

Update inventory for bst2-dcp:
  stage: update_inventory
  variables:
    inventory_repository_name: pcss-data-space-bst2-dcp-inventory
    inventory_hostname: $inventory_hostname_pcss_bst2_dcp
    gitlab_push_token: $gitlab_push_token_pcss_bst2_dcp
  script:
    - devlab_update_inventory
  only:
    variables:
      - $CI_COMMIT_BRANCH == $branch_allowed_to_update_inventory_pcss_bst2_dcp

integration-test:
  stage: test
  image: docker:latest
  rules:
    - when: never
  services:
    - docker:dind
  variables:
    CI_IMAGE_TAG: $CI_IMAGE_TAG
    CI_PROJECT_DIR: $CI_REPO_DIR
    CI_REGISTRY_DOMAIN: $CI_REGISTRY_DOMAIN
  script:
    - cd ${CI_PROJECT_DIR}/bin
    - ./devtests up --abort-on-container-exit --exit-code-from integration-tests
