# default:
#   image: registry.paas.psnc.pl/devlab/gitlab-runner:v1

default:
  image: registry.paas.psnc.pl/devlab/gitlab-runner:branch-increase_ulimit

variables:
  GIT_STRATEGY: clone

stages:
  - precommit
  - build
  - upload
  - update_inventory

Run pre-commit check:
  stage: precommit
  script:
    - devlab_run_pre_commit 2500
  artifacts:
    paths:
      - ./reports

Build images:
  stage: build
  script:
    - devlab_build_images

Upload images:
  stage: upload
  script:
    - devlab_push_images

Update inventory for main project:
  stage: update_inventory
  variables:
    inventory_repository_name: inventory
    inventory_hostname: $inventory_hostname
    gitlab_push_token: $gitlab_push_token_dev
  script:
    - devlab_update_inventory
  only:
    variables:
      - $CI_COMMIT_BRANCH == $branch_allowed_to_update_inventory

# Update inventory for atos-psnc integration:
#   stage: update_inventory
#   variables:
#     inventory_repository_name: atos-integration-inventory
#     inventory_hostname: $inventory_hostname_psnc_atos
#     gitlab_push_token: $gitlab_push_token_psnc_atos
#   script:
#     - devlab_update_inventory
#   only:
#     variables:
#       - $CI_COMMIT_BRANCH == $branch_allowed_to_update_inventory_atos_psnc