default:
  image: registry.paas.psnc.pl/devlab/gitlab-runner:v1

variables:
  GIT_STRATEGY: clone

stages:
  - precommit
  - build
  - test
  - upload
  - update_inventory

Run pre-commit check:
  stage: precommit
  script:
    - devlab_run_pre_commit 2500
  artifacts:
    paths:
      - ./reports

Build images:
  stage: build
  variables:
    ULIMIT_NOFILE: "16384:16384"
  script:
    - devlab_build_images

Upload images:
  stage: upload
  script:
    - devlab_push_images

Update inventory for main project:
  stage: update_inventory
  variables:
    inventory_repository_name: inventory
    inventory_hostname: $inventory_hostname_psnc
    gitlab_push_token: $gitlab_push_token_dev
  script:
    - devlab_update_inventory
  only:
    variables:
      - $CI_COMMIT_BRANCH == $branch_allowed_to_update_inventory

Update inventory for atos-psnc integration:
  stage: update_inventory
  variables:
    inventory_repository_name: atos-integration-inventory
    inventory_hostname: $inventory_hostname_psnc_atos
    gitlab_push_token: $gitlab_push_token_psnc_atos
  script:
    - devlab_update_inventory
  only:
    variables:
      - $CI_COMMIT_BRANCH == $branch_allowed_to_update_inventory_atos_psnc

integration-test:
  stage: test
  image: docker:latest
  services:
    - docker:dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  before_script:
    - apk add --no-cache curl jq docker-compose
  script:
    - cd ${CI_PROJECT_DIR}/docker
    - make build
    - cd ../bin
    - ./devstack up -d
    - ./tests
    - ./devstack logs > docker-compose.log
    - ./devstack down
  artifacts:
    when: always
    paths:
      - docker-compose.log
      - tests/test.log
