edc.participant.id=did:web:fc-ih%3A7183
edc.iam.sts.oauth.client.secret.alias=did:web:fc-ih%3A7183-sts-client-secret
edc.iam.sts.oauth.client.id=did:web:fc-ih%3A7183
edc.iam.sts.oauth.token.url=http://fc-ih:7188/oauth2/token
edc.iam.issuer.id=did:web:fc-ih%3A7183
edc.iam.sts.privatekey.alias=key-1
edc.iam.sts.publickey.id=did:web:fc-ih%3A7183#key-1

web.http.port=8080
web.http.path=/api
web.http.catalog.port=8190
web.http.catalog.path=/api/catalog
web.http.management.port=8191
web.http.management.path=/api/management/
web.http.protocol.port=8192
web.http.protocol.path=/api/dsp
web.http.control.port=8193
web.http.control.path=/api/control
web.http.version.port=8195
web.http.version.path=/api/version
edc.api.auth.key=password
edc.iam.did.web.use.https=false
edc.dsp.callback.address=http://localhost:8192/api/dsp
edc.catalog.cache.execution.delay.seconds=5
edc.catalog.cache.execution.period.seconds=10
edc.mvd.participants.list.file=config/participants.json
edc.management.context.enabled=true

# dataplane specific config
edc.runtime.id=provider-qna-embedded-runtime
edc.transfer.proxy.token.verifier.publickey.alias=did:web:fc-ih%3A7183#key-1
edc.transfer.proxy.token.signer.privatekey.alias=did:web:fc-ih%3A7183-alias
edc.dpf.selector.url=http://localhost:8193/api/control/v1/dataplanes
web.http.public.port=12003
web.http.public.path=/api/public

edc.vault.hashicorp.url=http://fc-vault:8200
edc.vault.hashicorp.token=root