# control plane specific config
edc.iam.issuer.id=did:web:fc-ih%3A7103:piotr
web.http.port=8290
web.http.path=/api
web.http.management.port=8291
web.http.management.path=/api/management/
web.http.management.auth.type=tokenbased
web.http.management.auth.key=password
web.http.protocol.port=8292
web.http.protocol.path=/api/dsp
web.http.control.port=8293
web.http.control.path=/api/control
web.http.catalog.port=8294
web.http.catalog.path=/api/catalog
web.http.catalog_auth.type=tokenbased
web.http.catalog_auth.key=password
web.http.version.port=8295
web.http.version.path=/api/version
edc.iam.did.web.use.https=false
edc.iam.sts.privatekey.alias=did:web:fc-ih%3A7103:piotr-alias
edc.iam.sts.publickey.id=did:web:fc-ih%3A7103:piotr#key-1
edc.dsp.callback.address=http://federated-catalog:8292/api/dsp
edc.participant.id=did:web:fc-ih%3A7103:piotr
edc.catalog.cache.execution.delay.seconds=5
edc.catalog.cache.execution.period.seconds=45
edc.mvd.participants.list.file=config/participants.json
edc.management.context.enabled=true
edc.iam.sts.oauth.client.secret.alias=did:web:fc-ih%3A7103:piotr-sts-client-secret
edc.iam.sts.oauth.client.id=did:web:fc-ih%3A7103:piotr
edc.iam.sts.oauth.token.url=http://fc-ih:7106/api/sts/token

# dataplane specific config
edc.transfer.proxy.token.verifier.publickey.alias=did:web:fc-ih%3A7103:piotr#key-1
edc.transfer.proxy.token.signer.privatekey.alias=did:web:fc-ih%3A7103:piotr-alias
edc.dpf.selector.url=http://federated-catalog:8193/api/control/v1/dataplanes
web.http.public.port=13001
web.http.public.path=/api/public