# control plane specific config
edc.iam.issuer.id=did:web:fc-ih%3A7103:piotr
web.http.port=8290
web.http.path=/api
web.http.management.port=8291
web.http.management.path=/api/management/
web.http.protocol.port=8292
web.http.protocol.path=/api/dsp
web.http.control.port=8293
web.http.control.path=/api/control
web.http.catalog.port=8294
web.http.catalog.path=/api/catalog
web.http.version.port=8295
web.http.version.path=/api/version
web.http.targets.port=8296
web.http.targets.path=/api/targets
edc.iam.did.web.use.https=false
edc.iam.sts.privatekey.alias=key-1
edc.iam.sts.publickey.id=did:web:fc-ih%3A7103:piotr#key-1
edc.dsp.callback.address=http://federated-catalog:8292/api/dsp
edc.participant.id=did:web:fc-ih%3A7103:piotr
edc.catalog.cache.execution.delay.seconds=20
edc.catalog.cache.execution.period.seconds=60
edc.mvd.participants.list.file=config/participants.json
edc.management.context.enabled=true
edc.iam.sts.oauth.client.secret.alias=did:web:fc-ih%3A7103:piotr-sts-client-secret
edc.iam.sts.oauth.client.id=did:web:fc-ih%3A7103:piotr
edc.iam.sts.oauth.token.url=http://fc-ih:7106/api/sts/token

# control plane auth (tokenbased, delegated, composite, none)
web.http.auth.type=none
web.http.auth.includes=["tokenbased", "delegated"]
web.http.auth.key=password
web.http.auth.dac.key.url=http://identity-provider:48081/realms/Organizations/protocol/openid-connect/certs
web.http.auth.dac.audience=account

web.http.catalog.auth.type=none
web.http.catalog.auth.includes=["tokenbased", "delegated"]
web.http.catalog.auth.key=password
web.http.catalog.auth.dac.key.url=http://identity-provider:48081/realms/Organizations/protocol/openid-connect/certs
web.http.catalog.auth.dac.audience=account
# for some reason is required for .catalog context
web.http.management.auth.dac.audience=account

# dataplane specific config
edc.transfer.proxy.token.verifier.publickey.alias=did:web:fc-ih%3A7103:piotr#key-1
edc.transfer.proxy.token.signer.privatekey.alias=did:web:fc-ih%3A7103:piotr-alias
edc.dpf.selector.url=http://federated-catalog:8193/api/control/v1/dataplanes
web.http.public.port=13001
web.http.public.path=/api/public

# CORS
edc.web.rest.cors.enabled=true
edc.web.rest.cors.headers=origin,content-type,accept,authorization,x-api-key

# persistence
edc.sql.schema.autocreate=true
edc.sql.store.targetnodedirectory.datasource=default
edc.sql.store.federatedcatalog.datasource=default
edc.datasource.default.url=jdbc:postgresql://federated-catalog-postgres:5432/edc
edc.datasource.default.user=edc
edc.datasource.default.password=edc
edc.vault.hashicorp.url=http://fc-ih-vault:8200
edc.vault.hashicorp.token=hvs.6eIWbZ1M6Vj4yjiaq80bq6YF
edc.vault.hashicorp.token.ttl=0
edc.vault.hashicorp.token.scheduled-renew-enabled=false

# Audience validation config
web.http.catalog.auth.audience=federated-catalog
# web.http.catalog.auth.dac.audience=federated-catalog
web.http.catalog.auth.dac.key.url=http://data-space-keycloak:8080/realms/Organizations/protocol/openid-connect/certs
web.http.management.auth.dac.key.url=http://data-space-keycloak:8080/realms/Organizations/protocol/openid-connect/certs
