apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: pipelines-registration-service-service

resources:
- configmap.yaml
- route.yaml
- registration-service/configmap.yaml
- registration-service/pvc.yaml
- registration-service/deployment.yaml
- registration-service/service.yaml
