[metadata]
format.version = "1.1"

[versions]
awaitility = "4.3.0"
edc = "0.14.0"
edc-build = "1.0.0"
jackson = "2.18.2"
jakarta-json = "2.1.3"
parsson = "1.1.6"
postgres = "42.7.3"
restAssured = "5.5.6"
shared-extensions = "1.0.0"

[libraries]
# PSNC libs
psnc-auth-composite = { module = "com.psnc.mvds:auth-composite", version.ref = "shared-extensions" }
psnc-vault-keys-seeder = { module = "com.psnc.mvds:vault-keys-seeder", version.ref = "shared-extensions" }
psnc-dcp-impl = { module = "com.psnc.mvds:dcp-impl", version.ref = "shared-extensions" }

# EDC libs
# standard
edc-configuration-filesystem = { module = "org.eclipse.edc:configuration-filesystem", version.ref = "edc" }

# apis
edc-api-secrets = { module = "org.eclipse.edc:secrets-api", version.ref = "edc" }
edc-api-management-config = { module = "org.eclipse.edc:management-api-configuration", version.ref = "edc" }
edc-api-management = { module = "org.eclipse.edc:management-api", version.ref = "edc" }

# controlplane
edc-controlplane-core = { module = "org.eclipse.edc:control-plane-core", version.ref = "edc" }
edc-controlplane-services = { module = "org.eclipse.edc:control-plane-aggregate-services", version.ref = "edc" }

# core
edc-core-edrstore = { module = "org.eclipse.edc:edr-store-core", version.ref = "edc" }
edc-dsp = { module = "org.eclipse.edc:dsp", version.ref = "edc" }
edc-api-dsp-config = { module = "org.eclipse.edc:dsp-http-api-configuration-2025", version.ref = "edc" }

edc-boot = { module = "org.eclipse.edc:boot", version.ref = "edc" }
edc-core-connector = { module = "org.eclipse.edc:connector-core", version.ref = "edc" }
edc-core-runtime = { module = "org.eclipse.edc:runtime-core", version.ref = "edc" }
edc-core-api = { module = "org.eclipse.edc:api-core", version.ref = "edc" }
edc-ext-http = { module = "org.eclipse.edc:http", version.ref = "edc" }
edc-api-observability = { module = "org.eclipse.edc:api-observability", version.ref = "edc" }
edc-ext-jsonld = { module = "org.eclipse.edc:json-ld", version.ref = "edc" }
edc-core-token = { module = "org.eclipse.edc:token-core", version.ref = "edc" }
edc-config-fs = { module = "org.eclipse.edc:configuration-filesystem", version.ref = "edc" }
edc-oauth2-client = { module = "org.eclipse.edc:oauth2-client", version.ref = "edc" }
edc-dcp-core = { module = "org.eclipse.edc:identity-trust-core", version.ref = "edc" }

# dcp
edc-dcp = { module = "org.eclipse.edc:identity-trust-service", version.ref = "edc" }
edc-did-core = { module = "org.eclipse.edc:identity-did-core", version.ref = "edc" }
edc-did-web = { module = "org.eclipse.edc:identity-did-web", version.ref = "edc" }

# EDC Postgres modules
edc-sql-core = { module = "org.eclipse.edc:sql-core", version.ref = "edc" }
edc-sql-lease = { module = "org.eclipse.edc:sql-lease", version.ref = "edc" }
edc-sql-pool = { module = "org.eclipse.edc:sql-pool-apache-commons", version.ref = "edc" }
edc-sql-transactionlocal = { module = "org.eclipse.edc:transaction-local", version.ref = "edc" }
edc-target-node-directory-sql = { module = "org.eclipse.edc:target-node-directory-sql", version.ref = "edc" }
edc-federated-catalog-cache-sql = { module = "org.eclipse.edc:federated-catalog-cache-sql", version.ref = "edc" }
edc-sql-bootstrapper = { module = "org.eclipse.edc:sql-bootstrapper", version.ref = "edc" }

# persistence
edc-vault-hashicorp = { module = "org.eclipse.edc:vault-hashicorp", version.ref = "edc" }
edc-sts-remote-client = { module = "org.eclipse.edc:identity-trust-sts-remote-client", version.ref = "edc" }

# third-party libs
postgres = { module = "org.postgresql:postgresql", version.ref = "postgres" }

# dcp-impl
edc-spi-identity-trust = { module = "org.eclipse.edc:identity-trust-spi", version.ref = "edc" }
edc-spi-transform = { module = "org.eclipse.edc:transform-spi", version.ref = "edc" }
edc-spi-catalog = { module = "org.eclipse.edc:catalog-spi", version.ref = "edc" }
edc-spi-identity-did = { module = "org.eclipse.edc:identity-did-spi", version.ref = "edc" }
edc-lib-jws2020 = { module = "org.eclipse.edc:jws2020-lib", version.ref = "edc" }
edc-lib-transform = { module = "org.eclipse.edc:transform-lib", version.ref = "edc" }

# did-example-resolver
edc-ih-spi-did = { module = "org.eclipse.edc:did-spi", version.ref = "edc" }

# federated catalog modules
edc-fc-spi-crawler = { module = "org.eclipse.edc:crawler-spi", version.ref = "edc" }
edc-fc-core = { module = "org.eclipse.edc:federated-catalog-core", version.ref = "edc" }
edc-fc-core2025 = { module = "org.eclipse.edc:federated-catalog-core-2025", version.ref = "edc" }
edc-fc-core08 = { module = "org.eclipse.edc:federated-catalog-core-08", version.ref = "edc" }
edc-fc-api = { module = "org.eclipse.edc:federated-catalog-api", version.ref = "edc" }

[bundles]
connector = [
    "edc-boot",
    "edc-core-connector",
    "edc-core-runtime",
    "edc-core-api",
    "edc-ext-http",
    "edc-api-observability",
    "edc-ext-jsonld",
    "edc-core-token",
    "edc-config-fs",
]

edc-sql-federatedcatalog = [
    "edc-target-node-directory-sql",
    "edc-federated-catalog-cache-sql",
    "edc-sql-core",
    "edc-sql-pool",
    "edc-sql-transactionlocal",
    "edc-sql-bootstrapper",
    "postgres",
]

dcp = [
    "edc-dcp",
    "edc-did-core",
    "edc-did-web",
    "edc-oauth2-client",
    "edc-dcp-core",
]

[plugins]
shadow = { id = "com.gradleup.shadow", version = "8.3.6" }
edc-build = { id = "org.eclipse.edc.edc-build", version.ref = "edc-build" }
