{% set parameters_existing_data = lookup('vars', parameters_data_var) %}

{% set accumulator = namespace(parameters_combined={}) %}
{% for inventory_varname in (query('varnames', '^' + parameters_owner + '_' + parameters_kind + '__\d\d_')|sort) %}
{% if not inventory_varname.endswith('_enabled_source') and lookup('vars', inventory_varname + '_enabled_source', default=true) %}
{% set accumulator.parameters_combined = accumulator.parameters_combined|combine(lookup('vars', inventory_varname)) %}
{% endif %}
{% endfor %}

{% for entry_name, entry_definition in accumulator.parameters_combined.items() %}
{% if entry_definition.when_missing is defined %}
{% if entry_name not in parameters_existing_data.keys() %}
{% if entry_definition.when_missing.generator|default(None) == 'keypair' %}
{% set private_key_base64 = lookup('pipe', 'openssl genrsa -out /dev/stdout 2048 2>/dev/null | base64 -w 0') %}
"{{ entry_name }}": '{{ private_key_base64 }}'
"{{ entry_definition.when_missing.arguments.public_key_parameter_name }}": '{{ lookup("pipe", "echo " + private_key_base64 + " | base64 -d | ssh-keygen -f /dev/stdin -y" ) }}'
{% else %}
"{{ entry_name }}": '{{ entry_definition.when_missing }}'
{% endif %}
{% endif %}
{% else %}
{% if entry_name not in parameters_existing_data or ((parameters_existing_data[entry_name]|b64decode) if parameters_kind == 'secret' else parameters_existing_data[entry_name]) != entry_definition %}
"{{ entry_name }}": '{{ entry_definition }}'
{% endif %}
{% endif %}
{% endfor %}
