from typing import Any, Dict, List, Literal, Optional

from pydantic import AnyHttpUrl, BaseModel, EmailStr, Field


class LocationRequest(BaseModel):
    """Request model for creating or updating a location."""

    country: Optional[str] = Field(..., max_length=2)  # ISO_CODE 3166 alpha_2 - pycountry
    city: Optional[str] = Field(..., max_length=100)
    postal_code: Optional[str] = Field(..., max_length=20)
    street: str = Field(..., max_length=200)
    building_number: Optional[str] = Field(..., max_length=20)


class ConnectorRequest(BaseModel):
    did: str = Field(..., description="Participant DID")
    name: Optional[str] = Field(None, description="Participant connector name")
    protocol_url: AnyHttpUrl = Field(..., description="Participant connector protocol URL")


class ParticipantCreateRequest(BaseModel):
    """Request model for creating a new participant."""

    ums_url: AnyHttpUrl = Field(..., description="Participant User Management Service URL")
    identity_hub_url: AnyHttpUrl = Field(..., description="Participant Identity Hub URL")
    name: str = Field(..., description="Participant name")
    full_name: str = Field(..., description="Participant full name")
    VAT_number: str = Field(..., description="Participant VAT number")
    email: EmailStr = Field(..., description="Participant contact email")
    location: LocationRequest = Field(None, description="Location info")
    connector: ConnectorRequest = Field(..., description="Participant connector info")


class ParticipantUpdateRequest(BaseModel):
    id: str = Field(..., description="Participant UUID")
    identity_hub_url: AnyHttpUrl = Field(..., description="Participant connector protocol URL")
    ums_url: AnyHttpUrl = Field(..., description="Participant User Management Service URL")
    name: str = Field(..., description="Participant name")
    full_name: str = Field(None, description="Participant full name")
    VAT_number: str = Field(None, description="Participant VAT number")
    email: EmailStr = Field(..., description="Participant contact email")
    location: LocationRequest = Field(None, description="Location info")
    connector: ConnectorRequest = Field(..., description="Participant connector info")


class VCRequest(BaseModel):
    """Request model for VC creation dedicated to single user."""

    connector_did: str = Field(..., description="DID of participant owning the connector")
    connector_token: str = Field(..., description="Token generated by connector to authenticate registration")
    claims: List[Dict[str, Any]] = Field(..., description="Claims about the user (email, name, subject, etc.)")
    vc_type: Literal["membership", "dataprocessor"] = Field(..., description="Type of VC to be issued")

class InsertVcRequest(BaseModel):
    connector_did: str = Field(..., description="DID of participant owning the connector")
    connector_dsp_url: str = Field(..., description="")
    connector_management_url: str = Field(..., description="")
    connector_api_key: str = Field(..., description="")
    identity_hub_identity_url: str = Field(..., description="")
    identity_hub_credentials_url: str = Field(..., description="")
    identity_hub_api_key: str = Field(..., description="")
    sts_public_key_pem: str = Field(..., description="")
    generated_vcs: List[Any] = Field(..., description="VC objects")