---
secrets:
  connector_db:
    postgres_user: "connector"
    postgres_password: "change-me-connector-db-password"
    postgres_db: "edc_connector_db"

  connector:
    datasource_default_url: "jdbc:postgresql://{{ connector_db_service }}:5432/edc_connector_db"
    datasource_default_user: "connector"
    datasource_default_password: "change-me-connector-db-password"
    iam_sts_oauth_client_secret: "change-me-sts-client-secret"
    vault_hashicorp_token: "change-me-connector-vault-token"
    api_auth_key: "change-me-api-key"

  keycloak_db:
    postgres_user: "keycloak"
    postgres_password: "change-me-keycloak-db-password"
    postgres_db: "keycloak"

  keycloak:
    admin: "admin"
    admin_password: "change-me-keycloak-admin-password"
    db: "postgres"
    db_schema: "public"
    db_url: "jdbc:postgresql://{{ keycloak_db_service }}:5432/keycloak"
    db_username: "keycloak"
    db_password: "change-me-keycloak-db-password"

  identity_hub_db:
    postgres_user: "edc"
    postgres_password: "change-me-identity-hub-db-password"
    postgres_db: "edc"

  identity_hub:
    vault_hashicorp_token: "change-me-identity-hub-vault-token"
    ih_api_superuser_key: "change-me-identity-hub-superuser-key"
    datasource_default_url: "jdbc:postgresql://{{ identity_hub_db_service }}:5432/edc"
    datasource_default_user: "edc"
    datasource_default_password: "change-me-identity-hub-db-password"

  storage:
    rustfs_access_key: "change-me-rustfs-access-key"
    rustfs_secret_key: "change-me-rustfs-secret-key"

  consumer_backend:
    s3_access_key: "change-me-rustfs-access-key"
    s3_secret_key: "change-me-rustfs-secret-key"