---
secrets:
  connector_db:
    postgres_user: "connector"
    postgres_password: "change-me-connector-db-password"
    postgres_db: "{{ connector_db_name }}"

  connector:
    datasource_default_url: "jdbc:postgresql://{{ connector_db_service }}:5432/{{ connector_db_name }}"
    datasource_default_user: "connector"
    datasource_default_password: "change-me-connector-db-password"
    vault_hashicorp_token: "leave-for-template"
    api_auth_key: "change-me-api-key"
    web_http_auth_key: "change-me-api-key"
    web_http_management_auth_key: "change-me-api-key"
    web_http_control_auth_key: "change-me-api-key"
    web_http_catalogproxy_auth_key: "change-me-api-key"

  keycloak_db:
    postgres_user: "keycloak"
    postgres_password: "change-me-keycloak-db-password"
    postgres_db: "keycloak"

  keycloak:
    admin: "admin"
    admin_password: "change-me-keycloak-admin-password"
    db: "postgres"
    db_schema: "public"
    db_url: "{{ keycloak_db_service }}"
    db_username: "keycloak"
    db_password: "change-me-keycloak-db-password"

  identity_hub_db:
    postgres_user: "edc"
    postgres_password: "change-me-identity-hub-db-password"
    postgres_db: "edc"

  identity_hub:
    vault_hashicorp_token: "leave-for-template"
    ih_api_superuser_key: "c3VwZXItdXNlcg==.c3VwZXItc2VjcmV0LWtleQo="
    datasource_default_user: "edc"
    datasource_default_password: "change-me-identity-hub-db-password"

  storage:
    rustfs_access_key: "change-me-rustfs-access-key"
    rustfs_secret_key: "change-me-rustfs-secret-key"

  consumer_backend:
    s3_access_key: "change-me-rustfs-access-key"
    s3_secret_key: "change-me-rustfs-secret-key"