from pydantic import BaseModel, AnyHttpUrl, Field
from typing import Optional, Dict, Any


class LocationRequest(BaseModel):
    """ Request model for creating or updating a location. """
    id: Optional[str] = Field(..., description="Location ID")
    country: Optional[str] = Field(None, max_length=100)
    city: Optional[str] = Field(None, max_length=100)
    postal_code: Optional[str] = Field(None, max_length=20)
    street: Optional[str] = Field(None, max_length=200)
    building_number: Optional[str] = Field(None, max_length=20)
    created_at: Optional[str] = Field(None, description="Creation timestamp")
    updated_at: Optional[str] = Field(None, description="Last update timestamp")


class ParticipantCreateRequest(BaseModel):
    """ Request model for creating a new participant. """
    did: Optional[str] = Field(..., description="Participant DID") # Created automatically
    protocol_url: AnyHttpUrl = Field(..., description="Participant connector registration/protocol URL")
    name: str = Field(..., description="Participant name")
    full_name: str = Field(None, description="Participant full name")
    VAT_number: str = Field(None, description="Participant VAT number")
    email: str = Field(..., description="Participant contact email")
    location: Optional[LocationRequest] = Field(None, description="Optional location info")
    created_at: Optional[str] = Field(None, description="Creation timestamp")
    updated_at: Optional[str] = Field(None, description="Last update timestamp")


class UserRegistrationForm(BaseModel):
    """ Request model for user registration form data. """
    username: str = Field(..., description="Username of the user")
    email: str = Field(..., description="Email of the user")
    full_name: Optional[str] = Field(None, description="Full name of the user")
    password: str = Field(..., description="Password of the user")


class UserRegistrationRequest(BaseModel):
    """ Request model for user registration via participant connector. """
    registration_form: UserRegistrationForm = Field(..., description="Format of the registration form")
    participant_did: str = Field(..., description="DID of participant owning the connector")
    connector_token: str = Field(..., description="Token generated by connector to authenticate registration")
    user_claims: Dict[str, Any] = Field(..., description="Claims about the user (email, name, subject, etc.)")
