from pydantic import BaseModel, AnyHttpUrl, Field
from typing import Optional, Dict, Any


class LocationRequest(BaseModel):
    """ Request model for creating or updating a location. """
    id: Optional[str] = Field(..., description="Location ID")
    country: Optional[str] = Field(None, max_length=100)
    city: Optional[str] = Field(None, max_length=100)
    postal_code: Optional[str] = Field(None, max_length=20)
    street: Optional[str] = Field(None, max_length=200)
    building_number: Optional[str] = Field(None, max_length=20)


class ContactRequest(BaseModel):
    """ Request model for creating or updating a contact. """
    id: Optional[str] = Field(..., description="Contact ID")
    email: Optional[str] = Field(..., description="Contact email address")
    phone_no: Optional[str] = Field(None, description="Contact phone number in E164 format")


class ParticipantCreateRequest(BaseModel):
    """ Request model for creating a new participant. """
    did: str = Field(..., description="Participant DID")
    protocol_url: AnyHttpUrl = Field(..., description="Participant connector registration/protocol URL")
    location: Optional[LocationRequest] = Field(None, description="Optional location info")
    contact: Optional[ContactRequest] = Field(None, description="Optional contact info")


class UserRegistrationRequest(BaseModel):
    """ Request model for user registration via participant connector. """
    participant_did: str = Field(..., description="DID of participant owning the connector")
    connector_token: str = Field(..., description="Token generated by connector to authenticate registration")
    connector_callback_url: AnyHttpUrl = Field(..., description="Connector endpoint where RS should POST the generated VC")
    user_claims: Dict[str, Any] = Field(..., description="Claims about the user (email, name, subject, etc.)")
    ttl_seconds: Optional[int] = Field(3600, description="Lifetime for issued VC in seconds")
