
REGISTRY_DOMAIN?=registry.paas.psnc.pl
REGISTRY_PROJECT?=demeter
REGISTRY_APPLICATION?=edc-connector

BASE_IMAGE_REGISTRY_DOMAIN?=$(REGISTRY_DOMAIN)
BASE_IMAGE_REGISTRY_PROJECT?=base

build-base: CONTEXT_PATH=../

build-base: build-base-builder
build-base: BUILDER_IMAGE=$(REGISTRY_DOMAIN)/$(REGISTRY_PROJECT)/$(REGISTRY_APPLICATION)/base-builder:$(BUILD_TIME_TAG)

build-base: BASE_IMAGE_SUFFIX_REPOSITORY_SUFFIX=almalinux:9

build-postgres: BASE_IMAGE_SUFFIX_REPOSITORY_SUFFIX=postgres:11

build-connector: BUILDER_IMAGE=$(REGISTRY_DOMAIN)/base/bellsoft/liberica-openjdk-debian:17-cds
build-connector: CONTEXT_PATH=../

build-base build-postgres: BASE_IMAGE=$(BASE_IMAGE_REGISTRY_DOMAIN)/$(BASE_IMAGE_REGISTRY_PROJECT)/$(BASE_IMAGE_SUFFIX_REPOSITORY_SUFFIX)
build-connector: BASE_IMAGE=$(BUILDER_IMAGE)

build-federated-catalog: BUILDER_IMAGE=$(REGISTRY_DOMAIN)/base/bellsoft/liberica-openjdk-debian:17-cds
build-federated-catalog: CONTEXT_PATH=../
build-federated-catalog: BASE_IMAGE=$(BUILDER_IMAGE)

build-data-space-hub: BUILDER_IMAGE=$(REGISTRY_DOMAIN)/base/python:3.13-alpine
build-data-space-hub: CONTEXT_PATH=../
build-data-space-hub: BASE_IMAGE=$(BUILDER_IMAGE)

build-registration-service-frontend: BUILDER_IMAGE=$(REGISTRY_DOMAIN)/base/node:lts
build-registration-service-frontend: BASE_IMAGE=$(REGISTRY_DOMAIN)/base/nginxinc/nginx-unprivileged
build-registration-service-frontend: CONTEXT_PATH=../

build-data-dashboard: BUILDER_IMAGE=$(REGISTRY_DOMAIN)/base/node:lts
build-data-dashboard: BASE_IMAGE=$(REGISTRY_DOMAIN)/base/nginxinc/nginx-unprivileged
build-data-dashboard: CONTEXT_PATH=../

build-consumer-backend: BUILDER_IMAGE=$(REGISTRY_DOMAIN)/base/python:3.9-slim
build-consumer-backend: CONTEXT_PATH=../

build-data-source: BUILDER_IMAGE=$(REGISTRY_DOMAIN)/base/python:3.9-slim
build-data-source: CONTEXT_PATH=../

build-minio: BASE_IMAGE_SUFFIX_REPOSITORY_SUFFIX=minio/minio:RELEASE.2025-09-07T16-13-09Z
build-minio: BASE_IMAGE=$(BASE_IMAGE_REGISTRY_DOMAIN)/$(BASE_IMAGE_REGISTRY_PROJECT)/$(BASE_IMAGE_SUFFIX_REPOSITORY_SUFFIX)

build-identity-hub: BUILDER_IMAGE=$(REGISTRY_DOMAIN)/base/openjdk:17-slim-bullseye
build-identity-hub: CONTEXT_PATH=../
build-identity-hub: BASE_IMAGE=$(BUILDER_IMAGE)

build-issuer-service: BUILDER_IMAGE=$(REGISTRY_DOMAIN)/base/openjdk:17-slim-bullseye
build-issuer-service: CONTEXT_PATH=../
build-issuer-service: BASE_IMAGE=$(BUILDER_IMAGE)