#!/bin/bash
set -e

name=${1:?provide symbolic name for installation}
path=${2:?provide installation path}
shift 2
files="$@"

initial_file="/etc/cont-init.d/10-$name"
install_script="/usr/local/bin/auto-pip-$name"

if [ -e $initial_file ]
then
	echo "initial script $initial_file already exists"
	exit 1
fi

if [ -e $install_script ]
then
	echo "install script $install_script already exists"
	exit 1
fi

cd $path

freeze_dir="/etc/auto-pip.d/$name"

mkdir -p "$freeze_dir"

command="pip install"
for file in $files
do
	if [ ! -e "$file" ]
	then
		echo "file $file is missing"
		exit 1
	fi
	mkdir -p $freeze_dir/`dirname $file`
	cp $file $freeze_dir/$file
	command+=" -r $file"
done

cat <<EOF > $install_script
#!/bin/bash
set -e
cd $path
if [ -e "venv/bin/activate" ]
then
	. venv/bin/activate
fi
exec $command
EOF

# with-contenv below is important to properly pass environment
# especially LD_LIBRARY_PATH

cat <<EOF > $initial_file
#!/usr/bin/with-contenv bash
set -e
files="$files"
freeze_dir=$freeze_dir
install_script=$install_script

cd $path
EOF

cat <<'EOF' >> $initial_file
install=0
for file in $files
do
	frozen_file=$(realpath $freeze_dir/$file)
	if diff $frozen_file $file
	then
		echo "files $frozen_file and $file are the same"
	else
		echo "files $frozen_file and $file are different - will reinstall"
		install=1
	fi
done

if [ "$install" -eq "1" ]
then
	echo "reinstalling"
	exec $install_script
else
	exit 0
fi

EOF

chmod a+x $initial_file
chmod a+x $install_script
