#!/bin/bash

source /srv/venv/bin/activate

REPORTS_DIR=/srv/reports
TEST_DIR=/srv/src

# run tests gathering coverage data
coverage run -m pytest -vv -ra --junitxml=$REPORTS_DIR/junit.xml $TEST_DIR "$@"
result=$?

# plain text report
coverage report | tee $REPORTS_DIR/coverage.txt

# make html report
coverage html -d $REPORTS_DIR/coverage.html

# make xml report
coverage xml -o $REPORTS_DIR/coverage.xml

exit $result
