#!/bin/bash

if [ ! -e /etc/services.d/runserver ]
then
	echo "impostor is currently compatible only with the runserver service - exiting"
	exit 1
fi

echo "stoping original service "
touch /var/run/impostor-sentinel

s6-svc -d -wD /etc/services.d/runserver

pkill -f 'python manage.py runserver'

rm /var/run/impostor-sentinel

while true
do
	echo "running runserver"
	manage runserver 0.0.0.0:9001
	echo -e "\nimpostor runserver returned with exit code: $?"
	echo "choose what to do next:"
	action='restart service'
	select action in 'run impostor again' 'restart service' 'shutdown container' 'leave container'
	do
		if [ "$action" != "" ]
		then
			break
		fi
	done

	echo "chosen action: $action"

	if [ "$action" != "run impostor again" ]
	then
		break
	fi

done

case "$action" in
	( "" | "shutdown container" )
		echo "shutting down container"
		exec shutdown-container
		;;
	("restart service")
		echo "restarting service"
		s6-svc -u -wU /etc/services.d/runserver
		echo "service restarted"
		;;
	("leave container")
		echo "leaving container running with no service running inside - you should probably do something more now or face the consequences"
		;;
esac
