---
- name: deploy stateless services
  hosts: edc-connector-instances

  vars:
    horizontal_pod_autoscalers_state: "{{ 'present' if with_stateless_services_horizontal_pod_autoscalers else 'absent' }}"
    horizontal_pod_autoscalers_task_heading: "{{ 'deploy' if with_stateless_services_horizontal_pod_autoscalers else 'purge' }}"

  module_defaults:
    k8s:
      wait: true
      wait_timeout: "{{ k8s_wait_timeout }}"
      state: present
      namespace: "{{ k8s_namespace }}"

  tasks:
    - name: "fetch image_tag if undefined"
      # TODO DV-272 remove this or here
      when: image_tag is undefined or not image_tag
      include_tasks: "tasks/fetch-current-image-tag.yaml"
