---
- name: deploy stateless services
  hosts: "{{ lookup('env', 'edc_connector_instances_target') }}"

  vars:
    horizontal_pod_autoscalers_state: "{{ 'present' if with_stateless_services_horizontal_pod_autoscalers else 'absent' }}"
    horizontal_pod_autoscalers_task_heading: "{{ 'deploy' if with_stateless_services_horizontal_pod_autoscalers else 'purge' }}"

  module_defaults:
    k8s:
      wait: true
      wait_timeout: "{{ k8s_wait_timeout }}"
      state: present
      namespace: "{{ k8s_namespace }}"

  # deployed_parameters_packs is defining wheter a given service is deployed or not, it is located in group_vars/edc-connector-instances-<cluster>.yaml
  tasks:
    #consumer
    - include_tasks: deploy-stateless-tasks/data-space-keycloak.yaml
      when: "'dataspacekeycloak' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/consumer-keycloak.yaml
      when: "'consumerkeycloak' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/provider-keycloak.yaml
      when: "'providerkeycloak' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/consumer-dashboard.yaml
      when: "'consumerdashboard' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/consumer-connector.yaml
      when: "'connectorconsumer' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/consumer-identity-hub.yaml
      when: "'identityhubconsumer' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/consumer-identity-provider.yaml
      when: "'identityproviderconsumer' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/consumer-backend.yaml
      when: "'consback' in (deployed_parameters_packs | from_yaml)"
    #provider
    - include_tasks: deploy-stateless-tasks/provider-dashboard.yaml
      when: "'providerdashboard' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/provider-connector.yaml
      when: "'connectorprovider' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/provider-identity-hub.yaml
      when: "'identityhubprovider' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/provider-identity-provider.yaml
      when: "'identityproviderprovider' in (deployed_parameters_packs | from_yaml)"
    #authority
    - include_tasks: deploy-stateless-tasks/federated-catalog.yaml
      when: "'federatedcatalog' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/federated-catalog-identity-hub.yaml
      when: "'identityhubfederatedcatalog' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/data-space-hub.yaml
      when: "'dataspacehub' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/data-space-portal.yaml
      when: "'dataspaceportal' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/mail-service.yaml
      when: "'mailservice' in (deployed_parameters_packs | from_yaml)"

    #used in daps
    - include_tasks: deploy-stateless-tasks/registration-service-backend.yaml
      when: "'registrationservicebackend' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/registration-service-frontend.yaml
      when: "'registrationservicefrontend' in (deployed_parameters_packs | from_yaml)"
    - include_tasks: deploy-stateless-tasks/identity-provider.yaml
      when: "'identityprovider' in (deployed_parameters_packs | from_yaml)"
