- name: Create OpenShift Routes
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ k8s_namespace }}"
        labels:
          app.kubernetes.io/part-of: "{{ application }}"
      spec:
        host: "{{ item.host }}"
        to:
          kind: Service
          name: "{{ item.service }}"
        port:
          targetPort: "{{ item.target_port | default('http') }}"
        tls:
          termination: edge
          insecureEdgeTerminationPolicy: Allow
  loop: "{{ routes }}"
  loop_control:
    label: "{{ item.name }}"
