---
- import_playbook: "unwitting-purge-protector.yaml"
  vars:
    purge_subject: "stateful services"

- name: purge storage services
  hosts: edc-connector-instances
  module_defaults:
    k8s:
      wait: true
      state: absent
      namespace: "{{ k8s_namespace }}"
#
#  tasks:
#    - name: "purge service/{{ application }}-memcached"
#      when: "deploy_memcached"
#      tags:
#        - memcached
#        - service
#      k8s:
#        definition:
#          apiVersion: v1
#          kind: Service
#          metadata:
#            name: "{{ application }}-memcached"
