---
- hosts: edc-connector-instances
  vars_prompt:

    - name: docker_server
      prompt: "Pass domain of the docker server (here or -e docker_server=)"
      private: no

    - name: docker_username
      prompt: "Pass username (here or -e docker_username=)"
      private: no

    - name: docker_password
      prompt: "Pass password (here or -e docker_password=)"
      private: yes

  tasks:

    - name: create secret
      shell: >
        {{ kubectl_command }} -n {{ k8s_namespace }} create secret docker-registry {{ image_pull_secret }} --docker-server {{ docker_server }} --docker-username '{{ docker_username }}' --docker-password '{{ docker_password }}'

    - name: attach secret to the default serviceaccount
      shell: >
        {{ kubectl_command }} -n {{ k8s_namespace }} secrets add serviceaccount/default secrets/{{ image_pull_secret }} --for=pull
