---
- hosts: edc-connector-instances
  vars_prompt:

    - name: upload_tls_secret_name
      prompt: "Name of the K8S secret (by default value of expose_http_tls_secret_name variable will be used)"
      private: no
      default: ""

    - name: upload_tls_cert
      prompt: "Name of the file containg certificate"
      private: no

    - name: upload_tls_key
      prompt: "Name of the file containg key"
      private: no

  tasks:

    - name: upload certificate
      shell: >
        oc -n {{ k8s_namespace }} create secret tls {{ upload_tls_secret_name|default(expose_http_tls_secret_name, true) }} --key {{ upload_tls_key }} --cert {{ upload_tls_cert }}
