#!/usr/bin/with-contenv /bin/bash
set -e

# http://www.gtopia.org/blog/2010/02/der-vs-crt-vs-cer-vs-pem-certificates/

DOMAIN=${1:?domain}
OUTPUT_DIR=${2:-/etc/certs}
PEM_PATH=${3:-${OUTPUT_DIR}/${DOMAIN}.hitch-pem}
CER_PATH=${4:-${OUTPUT_DIR}/${DOMAIN}.cer}
KEY_PATH=${5:-${OUTPUT_DIR}/${DOMAIN}.key}
CSR_PATH=${6:-${OUTPUT_DIR}/${DOMAIN}.csr}

if [ -e $PEM_PATH ]
then
	echo "certificate $PEM_PATH exists - skipping"
	exit 0
fi

echo "generating certificate $PEM_PATH"


SUBJ="/C=PL/ST=Wielkopolskie/O=PSNC/localityName=Poznan/commonName=$DOMAIN/organizationalUnitName=/emailAddress=/"

openssl genrsa -out $KEY_PATH 2048
echo generated
openssl req -new -subj $SUBJ -key $KEY_PATH -out $CSR_PATH
openssl x509 -req -days 365 -in $CSR_PATH -signkey $KEY_PATH -out $CER_PATH
cat $KEY_PATH $CER_PATH > $PEM_PATH
