"""add email_confirmation for participant, add ums_url related to participant and protocol_url->list

Revision ID: 425360d1fa83
Revises: 7721ae872554
Create Date: 2025-11-06 11:29:04.064658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '425360d1fa83'
down_revision: Union[str, Sequence[str], None] = '7721ae872554'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('ums_url', sa.String(), nullable=False))
    op.alter_column('participant', 'protocol_url',
               existing_type=sa.TEXT(),
               type_=sa.ARRAY(sa.String()),
               existing_nullable=False,
               postgresql_using='ARRAY[protocol_url]')
    op.add_column('registration_request', sa.Column('email_confirmed', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration_request', 'email_confirmed')
    op.alter_column('participant', 'protocol_url',
               existing_type=sa.ARRAY(sa.String()),
               type_=sa.TEXT(),
               existing_nullable=False,
               postgresql_using='ARRAY[protocol_url]')
    op.drop_column('participant', 'ums_url')
    # ### end Alembic commands ###
