"""add connector class and connect it to participant

Revision ID: 468b5c178f98
Revises: 425360d1fa83
Create Date: 2025-12-09 18:58:10.968135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '468b5c178f98'
down_revision: Union[str, Sequence[str], None] = '425360d1fa83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('connector',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('protocol_url', sa.String(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_connector_participant_id_participant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector'))
    )
    op.add_column('participant', sa.Column('identity_hub_url', sa.String(), nullable=False))
    op.drop_column('participant', 'protocol_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('protocol_url', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=False))
    op.drop_column('participant', 'identity_hub_url')
    op.drop_table('connector')
    # ### end Alembic commands ###
