"""email confirmation token

Revision ID: 6ac85914bcdd
Revises: 9627fb320297
Create Date: 2025-12-11 21:41:13.217496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ac85914bcdd'
down_revision: Union[str, Sequence[str], None] = '9627fb320297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_token',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.Column('consumed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['registration_request.id'], name=op.f('fk_registration_token_request_id_registration_request'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_token'))
    )
    op.create_index(op.f('ix_registration_token_consumed_at'), 'registration_token', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_registration_token_expires_at'), 'registration_token', ['expires_at'], unique=False)
    op.create_index(op.f('ix_registration_token_token'), 'registration_token', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_token_token'), table_name='registration_token')
    op.drop_index(op.f('ix_registration_token_expires_at'), table_name='registration_token')
    op.drop_index(op.f('ix_registration_token_consumed_at'), table_name='registration_token')
    op.drop_table('registration_token')
    # ### end Alembic commands ###
