"""remove contact, correct db fields

Revision ID: 7721ae872554
Revises: 20fff4247ad0
Create Date: 2025-10-28 15:18:07.039157

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "7721ae872554"
down_revision: Union[str, Sequence[str], None] = "20fff4247ad0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_participant_contact_id_contact"), "participant", type_="foreignkey")
    op.drop_table("contact")
    op.drop_column("issued_credentials", "username")
    op.add_column("participant", sa.Column("full_name", sa.String(length=500), nullable=False))
    op.add_column("participant", sa.Column("VAT_number", sa.String(length=50), nullable=False))
    op.add_column("participant", sa.Column("email", sa.String(length=255), nullable=False))
    op.drop_column("participant", "error_detail")
    op.drop_column("participant", "contact_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("participant", sa.Column("contact_id", sa.UUID(), autoincrement=False, nullable=True))
    op.add_column("participant", sa.Column("error_detail", sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column("participant", "email")
    op.drop_column("participant", "VAT_number")
    op.drop_column("participant", "full_name")
    op.add_column("issued_credentials", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_table(
        "contact",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("phone_no", sa.VARCHAR(length=25), autoincrement=False, nullable=True),
        sa.Column("created_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.Column("updated_at", postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
    )
    op.create_foreign_key(op.f("fk_participant_contact_id_contact"), "participant", "contact", ["contact_id"], ["id"])
    # ### end Alembic commands ###
