"""move did from participant to connector

Revision ID: 9627fb320297
Revises: 468b5c178f98
Create Date: 2025-12-10 13:53:23.480815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9627fb320297'
down_revision: Union[str, Sequence[str], None] = '468b5c178f98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('connector', sa.Column('did', sa.String(length=255), nullable=False))
    op.create_unique_constraint(op.f('uq_connector_did'), 'connector', ['did'])
    op.drop_constraint(op.f('uq_participant_did'), 'participant', type_='unique')
    op.drop_column('participant', 'did')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('did', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('uq_participant_did'), 'participant', ['did'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(op.f('uq_connector_did'), 'connector', type_='unique')
    op.drop_column('connector', 'did')
    # ### end Alembic commands ###
