"""remove connector table

Revision ID: b59521dc1cb9
Revises: 6ac85914bcdd
Create Date: 2026-02-05 21:55:53.728603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b59521dc1cb9'
down_revision: Union[str, Sequence[str], None] = '6ac85914bcdd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('connector')
    op.add_column('participant', sa.Column('data_space_components', sa.JSON(), nullable=True))
    op.drop_column('participant', 'ums_url')
    op.drop_column('participant', 'identity_hub_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('participant', sa.Column('identity_hub_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('participant', sa.Column('ums_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('participant', 'data_space_components')
    op.create_table('connector',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('protocol_url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('participant_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('did', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], name=op.f('fk_connector_participant_id_participant')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connector')),
    sa.UniqueConstraint('did', name=op.f('uq_connector_did'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
