X_API_KEY="email-123"
MAIL_USERNAME=<mail_username>
MAIL_PASSWORD=<mail_password>
MAIL_FROM=<mail_from> 
# PORT - default is 587
MAIL_PORT=<custom_port> 
MAIL_SERVER=<outcoming_email_server>
MAIL_FROM_NAME=<visible_sender_name>
