X_API_KEY=edc
MAIL_USERNAME=data.space.test.503039@gmail.com
MAIL_PASSWORD=bedpephpcgffqqax
MAIL_FROM=data.space.test.503039@gmail.com
# PORT - default is 587
MAIL_PORT=587
MAIL_SERVER=smtp.gmail.com
MAIL_FROM_NAME=PCSS Data Space
