# API
ISSUER_DID=did:web:data-space-hub%3A8000
API_CONTAINER_NAME=data-space-hub-api
PROJECT_NAME=data-sapce-hub
API_PORT=8000
POSTGRES_CONTAINER_NAME=dsh-postgres
SERVICE_NAME="Data Space HUB - PCSS"
FRONTEND_URL=http://localhost:5173

# postgres
POSTGRESQL_USERNAME=edc
POSTGRESQL_PASSWORD=edc
POSTGRESQL_HOST=data-space-hub-postgres
POSTGRESQL_PORT=5432
POSTGRESQL_DB=edc

# keycloak
KEYCLOAK_SERVER_URL=http://localhost:48081
KEYCLOAK_REALM=master
KEYCLOAK_CLIENT_ID=admin-cli
KEYCLOAK_CLIENT_SECRET=edc

# vault
VAULT_URL=http://data-space-hub-vault:8200
VAULT_ROLE_ID=http://data-space-hub-vault:8200
VAULT_SECRET_ID=http://data-space-hub-vault:8200
VAULT_KV_MOUNT=secret
VAULT_TRANSIT_MOUNT=transit
VAULT_TOKEN=root
VAULT_DEFAULT_KEY_TYPE=ed25519
VAULT_KEY_AUTO_ROTATE_DAYS=90
VAULT_NAMESPACE=admin
KEY_NAME=test_private_key

# digital_wallet
NODE_CONNECTION_ENDPOINT=some_endpoint

# email
EMAIL_USER=user@man.poznan.pl
EMAIL_PASSWORD=password
EMAIL_SERVICE_SEND_EMAIL_ENDPOINT=http://mail-service:5555/email
EMAIL_SERVICE_API_KEY=edc