# control plane specific config
edc.iam.issuer.id=did:web:consumer-ih%3A7083:alice
web.http.port=8080
web.http.path=/api
web.http.management.port=8081
web.http.management.path=/api/management/
web.http.protocol.port=8082
web.http.protocol.path=/api/dsp
web.http.control.port=8083
web.http.control.path=/api/control
web.http.catalog.port=8084
web.http.catalog.path=/api/catalog
web.http.version.port=8085
web.http.version.path=/api/version
edc.iam.did.web.use.https=false
edc.iam.sts.privatekey.alias=did:web:consumer-ih%3A7083:alice-alias
edc.iam.sts.publickey.id=did:web:consumer-ih%3A7083:alice#key-1
edc.dsp.callback.address=http://consumer-connector:8082/api/dsp
edc.participant.id=did:web:consumer-ih%3A7083:alice
edc.management.context.enabled=true
edc.iam.sts.oauth.client.secret.alias=did:web:consumer-ih%3A7083:alice-sts-client-secret
edc.iam.sts.oauth.client.id=did:web:consumer-ih%3A7083:alice
edc.iam.sts.oauth.token.url=http://consumer-ih:7086/api/sts/token

# control plane auth (tokenbased, delegated, composite, none)
web.http.auth.type=composite
web.http.auth.includes=["tokenbased", "delegated"]
web.http.auth.key=password
web.http.auth.dac.key.url=http://consumer-keycloak:48081/realms/Organizations/protocol/openid-connect/certs
web.http.auth.dac.audience=account

web.http.management.auth.type=composite
web.http.management.auth.includes=["tokenbased", "delegated"]
web.http.management.auth.key=password
web.http.management.auth.dac.key.url=http://consumer-keycloak:48081/realms/Organizations/protocol/openid-connect/certs
web.http.management.auth.dac.audience=account

web.http.control.auth.type=tokenbased
web.http.control.auth.key=password

# dataplane specific config
edc.transfer.proxy.token.verifier.publickey.alias=did:web:consumer-ih%3A7083:alice#key-1
edc.transfer.proxy.token.signer.privatekey.alias=did:web:consumer-ih%3A7083:alice-alias
edc.dpf.selector.url=http://consumer-connector:8083/api/control/v1/dataplanes
web.http.public.port=11001
web.http.public.path=/api/public

# CORS
edc.web.rest.cors.enabled=true
edc.web.rest.cors.headers=origin,content-type,accept,authorization,x-api-key

# persistence
edc.sql.schema.autocreate=true
edc.datasource.default.url = jdbc:postgresql://consumer-postgres:5432/edc
edc.datasource.default.user = edc
edc.datasource.default.password = edc