version: '3.8'

services:
  providerpostgres:
    image: docker.io/bitnami/postgresql:11
    restart: always
    environment:
      POSTGRESQL_USERNAME: edc
      POSTGRESQL_PASSWORD: edc
      POSTGRESQL_DATABASE: edc
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql-provider:/bitnami/postgresql'

  consumerpostgres:
    image: docker.io/bitnami/postgresql:11
    restart: always
    environment:
      POSTGRESQL_USERNAME: edc
      POSTGRESQL_PASSWORD: edc
      POSTGRESQL_DATABASE: edc
    ports:
      - '5433:5432'
    volumes:
      - 'postgresql-consumer:/bitnami/postgresql'

  connectorconsumer:
    image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/${REGISTRY_APPLICATION}/connector:${IMAGE_TAG}
    ports:
      - "29191:29191"
      - "29193:29193"
      - "29194:29194"
      - "29291:29291"
      - "29192:29192"
    volumes:
      - ../docker/connector/config/configuration-consumer.properties:/app/configuration.properties:ro
      - ../docker/connector/config/keystore.pfx:/app/keystore.pfx:ro
      - ../docker/connector/config/fs-consumer.vault:/app/fs.vault
    environment:
      EDC_FS_CONFIG: /app/configuration.properties
      EDC_API_AUTH_KEY: "fifi-info-zaneta"
    user: "1000:1000"

  consumerdashboard:
    image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/${REGISTRY_APPLICATION}/data-dashboard:${IMAGE_TAG}
    ports:
      - "28080:80"
    volumes:
      - ../src/data-dashboard/deployment/conf-consumer/consumer.nginx.conf:/etc/nginx/nginx.conf
      - ../src/data-dashboard/deployment/conf-consumer/consumer.config.json:/usr/share/nginx/html/assets/config/app.config.json
    user: "1000:1000"

  connectorprovider:
    image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/${REGISTRY_APPLICATION}/connector:${IMAGE_TAG}
    ports:
      - "19191:19191"
      - "19193:19193"
      - "19194:19194"
      - "19291:19291"
      - "19192:19192"
    volumes:
      - ../docker/connector/config/configuration-provider.properties:/app/configuration.properties:ro
      - ../docker/connector/config/keystore.pfx:/app/keystore.pfx:ro
      - ../docker/connector/config/fs-provider.vault:/app/fs.vault
      - ../docker/connector/config/api_collection.json:/app/api_collection.json
      - ../docker/connector/config/json_example.json:/app/json_example.json
    environment:
      EDC_FS_CONFIG: /app/configuration.properties
      EDC_API_AUTH_KEY: "fifi-info-zaneta"
    user: "1000:1000"

  providerdashboard:
    image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/${REGISTRY_APPLICATION}/data-dashboard:${IMAGE_TAG}
    ports:
      - "18080:80"
    volumes:
      - ../src/data-dashboard/deployment/conf-provider/provider.nginx.conf:/etc/nginx/nginx.conf
      - ../src/data-dashboard/deployment/conf-provider/provider.config.json:/usr/share/nginx/html/assets/config/app.config.json
    #   user: "1000"

  consumerbackend:
    image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/${REGISTRY_APPLICATION}/consumer-backend:${IMAGE_TAG}
    ports:
      - "4000:4000"
    environment:
      MINIO_ENDPOINT: "minio"
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio

  minio:
    image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/${REGISTRY_APPLICATION}/minio:${IMAGE_TAG}
    command: server /data
    environment:
      - HOSTNAME=minio
      - MINIO_ACCESS_KEY=minio-user
      - MINIO_SECRET_KEY=minio-password
    expose:
      - "9000"
    restart: unless-stopped

volumes:
  postgresql-provider:
    driver: local
  postgresql-consumer:
    driver: local
