version: '3.3'
services:

  postgres:
    restart: unless-stopped
    image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/${REGISTRY_APPLICATION}/postgres:${IMAGE_TAG}
    read_only: true
    user: "999"  # postgres user
    environment:
      - POSTGRES_PASSWORD=edc
      - POSTGRES_USER=edc
      - POSTGRES_DB=edc
    expose:
      - "5432"
    tmpfs:
      - "/run/postgresql"
      - "/tmp"

  consumer-connector:
    image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/${REGISTRY_APPLICATION}/connector:${IMAGE_TAG}
    restart: unless-stopped
    read_only: false
    environment:
      EDC_FS_CONFIG: /app/config/configuration-consumer.properties
      EDC_API_AUTH_KEY: "fifi-info-zaneta"

    ports:
      - "29191:29191"
      - "29193:29193"
      - "29194:29194"
      - "29291:29291"
      - "29192:29192"

  consumer-data-dashboard:
    image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/${REGISTRY_APPLICATION}/dashboard:${IMAGE_TAG}
    depends_on:
      - consumer-connector
    ports:
      - "28080:80"

networks:
  default:
