version: '3.3'
services:

  django:
    environment:
      - SRV_UWSGI_GEVENT=True
      - DATABASE_HOST=pgbouncer
      - DATABASE_PORT=5433
    depends_on:
      - pgbouncer

  pgbouncer:
    restart: unless-stopped
    image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/${REGISTRY_APPLICATION}/pgbouncer:${IMAGE_TAG}
    read_only: true
    user: "999"  # pgbouncer user
    environment:
      # see here:
      # https://pgbouncer.github.io/config.html
      # for available settings, and here:
      # see here https://github.com/brainsam/pgbouncer/blob/master/entrypoint.sh
      # for their names to use here
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USER=psql-user
      - DB_PASSWORD=psql-password
      - LISTEN_PORT=5433
      - LOG_CONNECTIONS=0
      - LOG_DISCONNECTIONS=0
      - POOL_MODE=transaction
      - STATS_PERIOD=5
      - UNIX_SOCKET_DIR=/var/lib/pgbouncer
    expose:
      - "5433"
    tmpfs:
      - "/var/lib/pgbouncer:uid=999"
    depends_on:
      - postgres
