"""initial

Revision ID: 0b3f59664d8a
Revises: 
Create Date: 2025-11-25 18:27:10.163882

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b3f59664d8a'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_requests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('error_detail', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('REQUESTED', 'REJECTED', 'APPROVED', 'ONBOARDED', name='registrationstatus'), nullable=True),
    sa.Column('request_form', sa.JSON(), nullable=True),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_requests'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('registration_requests')
    # ### end Alembic commands ###
