"""update registration tokens columns unique to False

Revision ID: 6f27cfa28693
Revises: ce3b1b90762b
Create Date: 2025-11-27 18:23:47.108231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6f27cfa28693'
down_revision: Union[str, Sequence[str], None] = 'ce3b1b90762b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_tokens_request_id'), table_name='registration_tokens')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_registration_tokens_request_id'), 'registration_tokens', ['request_id'], unique=True)
    # ### end Alembic commands ###
