"""add registration token columns expires_at consumed_at

Revision ID: ce3b1b90762b
Revises: df6577869c6f
Create Date: 2025-11-27 17:56:24.353071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3b1b90762b'
down_revision: Union[str, Sequence[str], None] = 'df6577869c6f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_tokens', sa.Column('expires_at', sa.TIMESTAMP(timezone=True), nullable=False))
    op.add_column('registration_tokens', sa.Column('consumed_at', sa.TIMESTAMP(timezone=True), nullable=True))
    op.create_index(op.f('ix_registration_tokens_consumed_at'), 'registration_tokens', ['consumed_at'], unique=False)
    op.create_index(op.f('ix_registration_tokens_expires_at'), 'registration_tokens', ['expires_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_tokens_expires_at'), table_name='registration_tokens')
    op.drop_index(op.f('ix_registration_tokens_consumed_at'), table_name='registration_tokens')
    op.drop_column('registration_tokens', 'consumed_at')
    op.drop_column('registration_tokens', 'expires_at')
    # ### end Alembic commands ###
