"""add registration token table

Revision ID: df6577869c6f
Revises: 0b3f59664d8a
Create Date: 2025-11-27 17:17:51.447211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df6577869c6f'
down_revision: Union[str, Sequence[str], None] = '0b3f59664d8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('registration_tokens',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['request_id'], ['registration_requests.id'], name=op.f('fk_registration_tokens_request_id_registration_requests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_registration_tokens'))
    )
    op.create_index(op.f('ix_registration_tokens_request_id'), 'registration_tokens', ['request_id'], unique=True)
    op.create_index(op.f('ix_registration_tokens_token'), 'registration_tokens', ['token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_tokens_token'), table_name='registration_tokens')
    op.drop_index(op.f('ix_registration_tokens_request_id'), table_name='registration_tokens')
    op.drop_table('registration_tokens')
    # ### end Alembic commands ###
