# API
ISSUER_DID=did:web:registration-service
API_CONTAINER_NAME=registration-service-api
PROJECT_NAME=registration-service
API_PORT=8000
POSTGRES_CONTAINER_NAME=registration-service-postgres
SERVICE_NAME="Registration Service"

# postgres
POSTGRESQL_CONTAINER_NAME=rs-postgres
POSTGRESQL_USERNAME=edc
POSTGRESQL_PASSWORD=edc
POSTGRESQL_HOST=registration-service-postgres
POSTGRESQL_PORT=5436
POSTGRESQL_DB=edc

# keycloak
KEYCLOAK_SERVER_URL=http://identity-provider:48081
KEYCLOAK_REALM=master
KEYCLOAK_CLIENT_ID=admin-cli
KEYCLOAK_CLIENT_SECRET=edc

# vault
VAULT_URL=http://localhost:7200
VAULT_ROLE_ID=http://localhost:7200
VAULT_SECRET_ID=http://localhost:7200
VAULT_KV_MOUNT=http://localhost:7200
VAULT_TOKEN=root

# digital_wallet
NODE_CONNECTION_ENDPOINT=some_endpoint


