# API
ISSUER_DID=did:web:data-space-hub
API_CONTAINER_NAME=data-space-hub-api
PROJECT_NAME=data-sapce-hub
API_PORT=8000
SERVICE_NAME="User Management Service - PCSS"
FRONTEND_URL=http://localhost:5173

# postgres
POSTGRESQL_USERNAME=edc
POSTGRESQL_PASSWORD=edc
POSTGRESQL_HOST=consumer-user-management-service-postgres
POSTGRESQL_PORT=5432
POSTGRESQL_DB=edc

# keycloak
KEYCLOAK_SERVER_URL=http://localhost:48081
KEYCLOAK_REALM=master
KEYCLOAK_CLIENT_ID=admin-cli
KEYCLOAK_CLIENT_SECRET=edc

# vault
VAULT_URL=http://localhost:7200
VAULT_ROLE_ID=http://localhost:7200
VAULT_SECRET_ID=http://localhost:7200
VAULT_KV_MOUNT=secret
VAULT_TRANSIT_MOUNT=transit
VAULT_TOKEN=root
VAULT_DEFAULT_KEY_TYPE=ed25519
VAULT_KEY_AUTO_ROTATE_DAYS=90
VAULT_NAMESPACE=admin

# digital_wallet
NODE_CONNECTION_ENDPOINT=some_endpoint

# email
EMAIL_SERVICE_SEND_EMAIL_ENDPOINT=http://mail-service:5555/email
EMAIL_SERVICE_API_KEY=edc

# identity hub
IDENTITY_HUB_DID=did:web:consumer-ih%3A7083
IDENTITY_HUB_CREDENTIALS_API_URL=http://consumer-ih:7081/api/credentials
IDENTITY_HUB_IDENTITY_API_URL=http://consumer-ih:7082/api/identity
IDENTITY_HUB_API_KEY=c3VwZXItdXNlcg==.c3VwZXItc2VjcmV0LWtleQo=