from typing import Any, Dict, List, Optional

from pydantic import AnyHttpUrl, BaseModel, Field, field_validator, EmailStr


class LocationRequest(BaseModel):
    """Request model for creating or updating a location."""

    country: Optional[str] = Field(..., max_length=2)  # ISO_CODE 3166 alpha_2 - pycountry
    city: Optional[str] = Field(..., max_length=100)
    postal_code: Optional[str] = Field(..., max_length=20)
    street: str = Field(..., max_length=200)
    building_number: Optional[str] = Field(..., max_length=20)


class UserCreateRequest(BaseModel):
    """Request model for creating a new user."""
    name: str = Field(..., description="Participant name")
    surname: str = Field(..., description="Participant surname")
    email: EmailStr = Field(..., description="Participant contact email")
    message: str = Field(..., description="Message to the admin")


class ParticipantUpdateRequest(BaseModel):
    id: str = Field(..., description="Participant UUID")
    protocol_url: List[AnyHttpUrl] = Field(..., description="Participant connector protocol URL")
    ums_url: AnyHttpUrl = Field(..., description="Participant User Management Service URL")
    name: str = Field(..., description="Participant name")
    full_name: str = Field(None, description="Participant full name")
    VAT_number: str = Field(None, description="Participant VAT number")
    email: str = Field(..., description="Participant contact email")
    location: LocationRequest = Field(None, description="Location info")


class UserInfoVCRequest(BaseModel):
    """Request model for VC creation dedicated to single user."""

    username: str = Field(..., description="Username")
    participant_did: str = Field(..., description="DID of participant owning the connector")
    connector_token: str = Field(..., description="Token generated by connector to authenticate registration")
    user_claims: Dict[str, Any] = Field(..., description="Claims about the user (email, name, subject, etc.)")
