---
application: edc-connector
ansible_connection: local
registry_project: demeter
registry_application: edc-connector
initial_replicas: 1
progress_deadline_seconds: 300
with_async_workers: true
use_environment_ingress_address: false
k8s_wait_timeout: 600

project_name: DEMETER
repository_name: edc-connector

base_image_registry_domain: "{{ registry_domain }}"
base_image_registry_project: "base"
connectorconsumer_init_containers_base_image: "{{ base_image_registry_domain }}/{{ base_image_registry_project }}/alpine:3.8"
connectorprovider_init_containers_base_image: "{{ base_image_registry_domain }}/{{ base_image_registry_project }}/alpine:3.8"
minio_init_containers_base_image: "{{ base_image_registry_domain }}/{{ base_image_registry_project }}/alpine:3.8"

readiness_probe_initial_delay: 3
readiness_probe_period: 15
readiness_probe_timeout: 10

liveness_probe_initial_delay: 30
liveness_probe_period: 30
liveness_probe_timeout: 60

with_stateless_services_horizontal_pod_autoscalers: true

connectorconsumer_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"

consumerdashboard_resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1"
    memory: "400Mi"

consback_resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1"
    memory: "400Mi"

minio_resources:
  requests:
    cpu: "1000m"
    memory: "300Mi"
  limits:
    cpu: "1500m"
    memory: "1Gi"

deploy_minio: true
is_auth: false

minio_pvc_storage_size: "2Gi"
minio_pvc_storage_class_name: ""

image_pull_secret: "regcred"
create_run_any_uid_service_account: true

MAIN_DOMAIN: "{{ inventory_hostname|regex_replace('-edc-connector-instance$', '') }}"

expose_http_kind: "routes"
expose_http_host: "{{ MAIN_DOMAIN }}"
# possible values: wildcard, static, acme, disabled
expose_http_tls_mode: 'wildcard'
expose_http_tls_redirect: true
expose_http_tls_allow_also_non_encrypted: false
expose_http_ip_whitelist: ""
expose_http_tls_secret_name: "{{ application }}-tls-secret"
expose_http_annotations: {}
expose_http_ingress_annotations: {}
expose_http_routes_annotations: {}
expose_http_name_prefix: "{{ application }}"
expose_http_k8s_entity_kind: "{{ 'Route' if expose_http_kind == 'routes' else 'Ingress' }}"
expose_http_k8s_entity_api_version: "{{ 'v1' if expose_http_kind == 'routes' else 'extensions/v1beta1' }}"

# Service adresses - modify if some adresses change
consumer_dashboard_address_shorten: "consumer-dashboard-edc-connector.apps.dcw1.paas.psnc.pl"
provider_dashboard_address_shorten: "ad4gd-dash-edc.dashboard-siba.store"
consumer_dashboard_address: "https://{{ consumer_dashboard_address_shorten }}"
provider_dashboard_address: "https://{{ provider_dashboard_address_shorten }}"
identity_provider_address: "https://keycloak-daps.dashboard-siba.store"
federated_catalog_address: "https://ad4gd-catalog-edc.dashboard-siba.store"
consumer_backend_address: "https://consback-edc-connector.apps.dcw1.paas.psnc.pl"
consumer_connector_address: "https://consumer-edc-connector.apps.dcw1.paas.psnc.pl"
provider_connector_address: "https://ad4gd-provider-edc.dashboard-siba.store"
minio_address: "https://edc-minio.apps.dcw1.paas.psnc.pl"

# TODO DV-272 remove KUBECTL_COMMAND
KUBECTL_COMMAND: kubectl
kubectl_command: "{{ KUBECTL_COMMAND }}"

# TODO DV-272 remove IMAGE_TAG
image_tag: "{{ application_version }}"
stateless_services_image_tag: "{{ image_tag }}"

# TODO DV-276: this should be a fixed value
stateful_services_image_tag: "{{ image_tag }}"
use_backup_velero_io_backup_volumes_annotation: false
use_minio_backup_velero_io_backup_volumes_annotation: false

stateless_services_image_pull_policy: "{{ 'IfNotPresent' if stateless_services_image_tag.startswith('commit-') else 'Always' }}"

ingress_scheme: "{{ 'https' if expose_http_tls_mode != 'disabled' else 'http' }}"

# TODO DV-272 remove ENVIRONMENT_INGRESS_ADDRESS
environment_ingress_address: "{{ ENVIRONMENT_INGRESS_ADDRESS|default('') }}"
ingress_address: "{{ environment_ingress_address if use_environment_ingress_address else MAIN_DOMAIN }}"

SENTRY_DSN: "https://132b6f2afb0c43b993b3f094c58a6658@sentry.apps.psnc.pl/6"

SECRET_KEY:
  when_missing: "{{ random_django_secret_key }}"

# DO NOT CHANGE DEFINITIONS BELOW

deployed_parameters_packs: "{{ ['connectorconsumer', 'consback', 'consumerdashboard', 'minio'] }}"

# definitions below are helper definitions - do not change this

# DO NOT CHANGE DEFINITIONS ABOVE
