---
deployment_profile: bst2-daps

application: edc-connector
ansible_connection: local
registry_project: demeter
registry_application: edc-connector
initial_replicas: 1
progress_deadline_seconds: 300
with_async_workers: true
use_environment_ingress_address: false
k8s_wait_timeout: 600

project_name: DEMETER
repository_name: edc-connector

base_image_registry_domain: "{{ registry_domain }}"
base_image_registry_project: "base"
connectorconsumer_init_containers_base_image: "{{ base_image_registry_domain }}/{{ base_image_registry_project }}/alpine:3.8"
connectorprovider_init_containers_base_image: "{{ base_image_registry_domain }}/{{ base_image_registry_project }}/alpine:3.8"
minio_init_containers_base_image: "{{ base_image_registry_domain }}/{{ base_image_registry_project }}/alpine:3.8"

readiness_probe_initial_delay: 3
readiness_probe_period: 15
readiness_probe_timeout: 10

liveness_probe_initial_delay: 30
liveness_probe_period: 30
liveness_probe_timeout: 60

with_stateless_services_horizontal_pod_autoscalers: true

connectorconsumer_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"

identityhubconsumer_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"

connectorprovider_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"

identityhubprovider_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"

connectorsage_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"

consumerdashboard_resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1"
    memory: "400Mi"

providerdashboard_resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1"
    memory: "400Mi"

sagedashboard_resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1"
    memory: "400Mi"

consback_resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1"
    memory: "400Mi"

minio_resources:
  requests:
    cpu: "1000m"
    memory: "300Mi"
  limits:
    cpu: "1500m"
    memory: "1Gi"

dataspacekeycloak_resources:
  requests:
    cpu: "100m"
    memory: "400Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

consumerkeycloak_resources:
  requests:
    cpu: "100m"
    memory: "400Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

providerkeycloak_resources:
  requests:
    cpu: "100m"
    memory: "400Mi"
  limits:
    cpu: "1"
    memory: "1Gi"

federatedcatalog_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"

registrationservicefrontend_resources:
  requests:
    cpu: "100m"
    memory: "200Mi"
  limits:
    cpu: "1"
    memory: "400Mi"

registrationservicebackend_resources:
  requests:
    cpu: "100m"
    memory: "1000Mi"
  limits:
    cpu: "1"
    memory: "2000Mi"

deploy_minio: true
is_auth: true

minio_pvc_storage_size: "2Gi"
minio_pvc_storage_class_name: ""

image_pull_secret: "regcred"
create_run_any_uid_service_account: true

MAIN_DOMAIN: "{{ inventory_hostname|regex_replace('-edc-connector-instance$', '') }}"

expose_http_kind: "routes"
expose_http_host: "{{ MAIN_DOMAIN }}"
# possible values: wildcard, static, acme, disabled
expose_http_tls_mode: 'wildcard'
expose_http_tls_redirect: true
expose_http_tls_allow_also_non_encrypted: false
expose_http_ip_whitelist: ""
expose_http_tls_secret_name: "{{ application }}-tls-secret"
expose_http_annotations: {}
expose_http_ingress_annotations: {}
expose_http_routes_annotations: {}
expose_http_name_prefix: "{{ application }}"
expose_http_k8s_entity_kind: "{{ 'Route' if expose_http_kind == 'routes' else 'Ingress' }}"
expose_http_k8s_entity_api_version: "{{ 'v1' if expose_http_kind == 'routes' else 'extensions/v1beta1' }}"

# Service adresses - modify if some adresses change
consumer_dashboard_address_shorten: "consumer-dashboard-edc-connector.apps.bst2.paas.psnc.pl"
provider_dashboard_address_shorten: "provider-dashboard-edc-connector.apps.bst2.paas.psnc.pl"
registration_service_frontend_address_shorten: "registration-service-edc-connector.apps.bst2.paas.psnc.pl"
sage_dashboard_address_shorten: "sage-dashboard-edc-connector.apps.bst2.paas.psnc.pl"
consumer_dashboard_address: "https://{{ consumer_dashboard_address_shorten }}"
provider_dashboard_address: "https://{{ provider_dashboard_address_shorten }}"
sage_dashboard_address: "https://{{ sage_dashboard_address_shorten }}"
registration_service_frontend_address: "https://{{ registration_service_frontend_address_shorten }}"
data_space_keycloak_address: "https://data-space-keycloak-edc-connector.apps.bst2.paas.psnc.pl"
consumer_keycloak_address: "https://consumer-keycloak-edc-connector.apps.bst2.paas.psnc.pl"
provider_keycloak_address: "https://provider-keycloak-edc-connector.apps.bst2.paas.psnc.pl"
federated_catalog_address: "https://federated-catalog-edc-connector.apps.bst2.paas.psnc.pl"
consumer_backend_address: "https://consumer-backend-edc-connector.apps.bst2.paas.psnc.pl"
consumer_connector_address: "https://consumer-connector-edc-connector.apps.bst2.paas.psnc.pl"
provider_connector_address: "https://provider-connector-edc-connector.apps.bst2.paas.psnc.pl"
sage_connector_address: "https://sage-connector-edc-connector.apps.bst2.paas.psnc.pl"
minio_address: "https://minio-edc-connector.apps.bst2.paas.psnc.pl"
registration_service_backend_address: "https://registration-service-api-edc-connector.apps.bst2.paas.psnc.pl"
# TODO DV-272 remove KUBECTL_COMMAND
KUBECTL_COMMAND: kubectl
kubectl_command: "{{ KUBECTL_COMMAND }}"

# TODO DV-272 remove IMAGE_TAG
image_tag: "{{ application_version }}"
stateless_services_image_tag: "{{ image_tag }}"

# TODO DV-276: this should be a fixed value
stateful_services_image_tag: "{{ image_tag }}"
use_backup_velero_io_backup_volumes_annotation: false
use_minio_backup_velero_io_backup_volumes_annotation: false

stateless_services_image_pull_policy: "{{ 'IfNotPresent' if stateless_services_image_tag.startswith('commit-') else 'Always' }}"

ingress_scheme: "{{ 'https' if expose_http_tls_mode != 'disabled' else 'http' }}"

# TODO DV-272 remove ENVIRONMENT_INGRESS_ADDRESS
environment_ingress_address: "{{ ENVIRONMENT_INGRESS_ADDRESS|default('') }}"
ingress_address: "{{ environment_ingress_address if use_environment_ingress_address else MAIN_DOMAIN }}"

SENTRY_DSN: "https://132b6f2afb0c43b993b3f094c58a6658@sentry.apps.psnc.pl/6"

SECRET_KEY:
  when_missing: "{{ random_django_secret_key }}"

# DO NOT CHANGE DEFINITIONS BELOW

deployed_parameters_packs: "{{ [
  'connectorconsumer',
  'connectorprovider',
  'connectorsage',
  'consback',
  'federatedcatalog',
  'consumerdashboard',
  'providerdashboard',
  'sagedashboard',
  'dataspacekeycloak',
  'consumerkeycloak',
  'providerkeycloak',
  'registrationservicefrontend',
  'registrationservicebackend'
  ] }}"

# definitions below are helper definitions - do not change this

# DO NOT CHANGE DEFINITIONS ABOVE
