---
- name: Apply secrets
  hosts: local
  gather_facts: false
  vars_files:
    - vars/shared_vars.yaml
    - vars/secrets.yaml

  vars:
    secrets_glob: "secrets/*.yaml"

  tasks:
    - name: Apply secrets from folder
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig_path }}"
        state: present
        namespace: "{{ k8s_namespace }}"
        definition: "{{ lookup('template', item) | from_yaml_all | list }}"
      loop: "{{ lookup('fileglob', secrets_glob, wantlist=True) | sort }}"
      when: lookup('fileglob', secrets_glob, wantlist=True) | length > 0
