---
- name: Deploy ingress routes
  hosts: local
  gather_facts: false
  vars_files:
    - vars/shared_vars.yaml

  module_defaults:
    kubernetes.core.k8s:
      kubeconfig: "{{ kubeconfig_path }}"
      state: present
      namespace: "{{ k8s_namespace }}"

  tasks:
    # Required section: connector + dashboard
    - name: Deploy connector ingress
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/connector/connector-ingress.yaml.j2') | from_yaml }}"

    - name: Deploy dashboard ingress
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/dashboard/dashboard-ingress.yaml.j2') | from_yaml }}"

    # Optional section: identity-provider = keycloak + keycloak DB
    - name: Deploy keycloak ingress
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/keycloak/keycloak-ingress.yaml.j2') | from_yaml }}"
      when: enable_identity_provider | bool

    # Optional section: identity-hub = identity-hub + vault + identity-hub DB
    - name: Deploy identity-hub ingress
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/identity-hub/identity-hub-ingress.yaml.j2') | from_yaml }}"
      when: enable_identity_hub | bool

    # Optional section: storage = storage + consumer-backend
    - name: Deploy storage ingress
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/storage/storage-ingress.yaml.j2') | from_yaml }}"
      when: enable_storage | bool

    - name: Deploy consumer-backend ingress
      kubernetes.core.k8s:
        definition: "{{ lookup('template', 'templates/storage/consumer-backend-ingress.yaml.j2') | from_yaml }}"
      when: enable_storage | bool
