---
- import_playbook: deploy-namespace.yaml
- import_playbook: deploy-secrets.yaml
- import_playbook: deploy-databases.yaml
- import_playbook: deploy-stateless-services.yaml
- import_playbook: deploy-routes.yaml
