web.http.port=7100
web.http.path=/api
web.http.credentials.port=7101
web.http.credentials.path=/api/credentials
web.http.identity.port=7102
web.http.identity.path=/api/identity
web.http.did.port=7103
web.http.did.path=/
web.http.version.port=7105
web.http.version.path=/api/version
web.http.sts.port=7106
web.http.sts.path=/api/sts
edc.iam.issuer.id = did:web:fc-ih%3A7103:piotr
edc.iam.did.web.use.https=false
edc.iam.sts.privatekey.alias=key-1
edc.iam.sts.publickey.id=did:web:fc-ih%3A7103:piotr#key-1
edc.ih.iam.publickey.path=/certs/fc_public.pem
edc.ih.iam.id=did:web:fc-ih%3A7103:piotr
edc.ih.api.superuser.key=c3VwZXItdXNlcg==.c3VwZXItc2VjcmV0LWtleQo=
edc.mvd.credentials.path=credentials/federated-catalog