web.http.port=7180
web.http.path=/api
web.http.credentials.port=7181
web.http.credentials.path=/api/credentials
web.http.identity.port=7182
web.http.identity.path=/api/identity
web.http.did.port=7183
web.http.did.path=/
web.http.version.port=7185
web.http.version.path=/api/version
web.http.sts.port=7186
web.http.sts.path=/api/sts
web.http.presentation.port=7187
web.http.presentation.path=/api/presentation
edc.iam.did.web.use.https=false
edc.iam.sts.privatekey.alias=key-1
edc.iam.sts.publickey.id=did:web:fc-ih%3A7183#key-1
edc.ih.iam.publickey.path=./certs/consumer_public.pem
edc.ih.iam.id=did:web:fc-ih%3A7183
edc.ih.api.superuser.key=c3VwZXItdXNlcg==.c3VwZXItc2VjcmV0LWtleQo=
edc.mvd.credentials.path=credentials/federated-catalog