apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${API_CONTAINER_NAME}
  namespace: pipelines-registration-service-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${API_CONTAINER_NAME}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ${API_CONTAINER_NAME}
    spec:
      containers:
      - name: ${API_CONTAINER_NAME}
        image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/${REGISTRY_APPLICATION}/${API_CONTAINER_NAME}:${BUILD_TAG}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "2Gi"
            cpu: "1"
          limits:
            memory: "3Gi"
            cpu: "2"
        ports:
        - containerPort: ${API_PORT}
        envFrom:
        - configMapRef:
            name: registration-service-service-config
        - configMapRef:
            name: registration-service-config
        command: ["python", "-m", "uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "${API_PORT}"]
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${CELERY_WORKER_CONTAINER_NAME}
  namespace: pipelines-registration-service-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${CELERY_WORKER_CONTAINER_NAME}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ${CELERY_WORKER_CONTAINER_NAME}
    spec:
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
      containers:
      - name: ${CELERY_WORKER_CONTAINER_NAME}
        image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/${REGISTRY_APPLICATION}/${API_CONTAINER_NAME}:${BUILD_TAG}
        imagePullPolicy: Always
        resources:
          requests:
            memory: "3Gi"
            cpu: "2"
          limits:
            memory: "10Gi"
            cpu: "8"
        envFrom:
        - configMapRef:
            name: registration-service-service-config
        - configMapRef:
            name: registration-service-config
        command: ["celery", "-A", "api.worker.celery_app", "worker", "--loglevel=info", "--concurrency=${CELERY_WORKER_COUNT}", "--max-tasks-per-child=1"]
      imagePullSecrets:
      - name: regcred
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${POSTGRES_CONTAINER_NAME}
  namespace: pipelines-registration-service-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${POSTGRES_CONTAINER_NAME}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: ${POSTGRES_CONTAINER_NAME}
    spec:
      containers:
      - name: ${POSTGRES_CONTAINER_NAME}
        image: ${REGISTRY_DOMAIN}/${REGISTRY_PROJECT}/${REGISTRY_APPLICATION}/${POSTGRES_CONTAINER_NAME}:${BUILD_TAG}
        imagePullPolicy: Always
        ports:
        - containerPort: ${POSTGRES_PORT}
        envFrom:
        - configMapRef:
            name: registration-service-service-config
        - configMapRef:
            name: registration-service-config
        volumeMounts:
        - name: postgres-data
          mountPath: /data/db
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: registration-service-postgres-pvc
      imagePullSecrets:
      - name: regcred
