apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registration-service-minio-pvc
  namespace: pipelines-registration-service-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: registration-service-mongo-pvc
  namespace: pipelines-registration-service-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
