apiVersion: v1
kind: Service
metadata:
  name: ${API_CONTAINER_NAME}
  namespace: pipelines-registration-service-service
spec:
  selector:
    app: ${API_CONTAINER_NAME}
  ports:
  - port: ${API_PORT}
    targetPort: ${API_PORT}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ${MINIO_CONTAINER_NAME}
  namespace: pipelines-registration-service-service
spec:
  selector:
    app: ${MINIO_CONTAINER_NAME}
  ports:
  - port: ${MINIO_PORT}
    targetPort: ${MINIO_PORT}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ${POSTGRES_CONTAINER_NAME}
  namespace: pipelines-registration-service-service
spec:
  selector:
    app: ${POSTGRES_CONTAINER_NAME}
  ports:
  - port: ${POSTGRES_PORT}
    targetPort: ${POSTGRES_PORT}
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: ${RABBITMQ_CONTAINER_NAME}
  namespace: pipelines-registration-service-service
spec:
  selector:
    app: ${RABBITMQ_CONTAINER_NAME}
  ports:
  - port: ${RABBIT_PORT_1}
    targetPort: ${RABBIT_PORT_1}
    name: amqp
  - port: ${RABBIT_PORT_2}
    targetPort: ${RABBIT_PORT_2}
    name: management
  type: ClusterIP
