#!/bin/bash
source /srv/audits/_audits_environment

setup_audit license

# TODO: DV-838 it should be here
# install_audit pip install pip-licenses==3.2.0

ALLOW_ONLY=$(sed -z 's/\n/;/g' /srv/audits/audit-license-allow-only.txt)
IGNORE_PACKAGES=$(sed -z 's/\n/ /g' /srv/audits/audit-license-ignore-packages.txt)

execute_audit pip-licenses --format plain --ignore-packages $IGNORE_PACKAGES --allow-only "$ALLOW_ONLY" --order license "$@"
