"""add registration_request

Revision ID: 20fff4247ad0
Revises: dda79f05c2f5
Create Date: 2025-10-23 16:58:08.185772

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20fff4247ad0"
down_revision: Union[str, Sequence[str], None] = "dda79f05c2f5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "registration_request",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("REQUESTED", "REJECTED", "APPROVED", "ONBOARDED", name="registrationstatus"),
            nullable=False,
        ),
        sa.Column("request_form", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_registration_request")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("registration_request")
    # ### end Alembic commands ###
