"""initial migration

Revision ID: 6efe6ced3d24
Revises:
Create Date: 2025-10-22 12:19:31.302942

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6efe6ced3d24"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contact",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("phone_no", sa.String(length=50), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_contact")),
    )
    op.create_table(
        "location",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("postal_code", sa.String(length=20), nullable=True),
        sa.Column("street", sa.String(length=200), nullable=True),
        sa.Column("building_number", sa.String(length=20), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_location")),
    )
    op.create_table(
        "participant",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("did", sa.String(length=255), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("protocol_url", sa.Text(), nullable=False),
        sa.Column("error_detail", sa.Text(), nullable=True),
        sa.Column("location_id", sa.UUID(), nullable=True),
        sa.Column("contact_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["contact_id"], ["contact.id"], name=op.f("fk_participant_contact_id_contact")),
        sa.ForeignKeyConstraint(["location_id"], ["location.id"], name=op.f("fk_participant_location_id_location")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_participant")),
        sa.UniqueConstraint("did", name=op.f("uq_participant_did")),
    )
    op.create_table(
        "issued_credentials",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("participant_id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(), nullable=False),
        sa.Column("credential_id", sa.UUID(), nullable=False),
        sa.Column("credential_hash", sa.String(), nullable=False),
        sa.Column("credential_storage_ref", sa.String(), nullable=True),
        sa.Column("issued_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("status", sa.Enum("ACTIVE", "REVOKED", "EXPIRED", name="credentialstatus"), nullable=False),
        sa.Column("credential_metadata", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(
            ["participant_id"], ["participant.id"], name=op.f("fk_issued_credentials_participant_id_participant")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_issued_credentials")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("issued_credentials")
    op.drop_table("participant")
    op.drop_table("location")
    op.drop_table("contact")
    # ### end Alembic commands ###
