"""add registration_request, country-iso_code

Revision ID: dda79f05c2f5
Revises: 6efe6ced3d24
Create Date: 2025-10-23 14:28:44.354108

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dda79f05c2f5"
down_revision: Union[str, Sequence[str], None] = "6efe6ced3d24"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "contact", "phone_no", existing_type=sa.VARCHAR(length=50), type_=sa.String(length=25), existing_nullable=True
    )
    op.alter_column(
        "location", "country", existing_type=sa.VARCHAR(length=100), type_=sa.String(length=2), existing_nullable=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "location", "country", existing_type=sa.String(length=2), type_=sa.VARCHAR(length=100), existing_nullable=True
    )
    op.alter_column(
        "contact", "phone_no", existing_type=sa.String(length=25), type_=sa.VARCHAR(length=50), existing_nullable=True
    )
    # ### end Alembic commands ###
