name: Local
variables:
  - name: CONSUMER_URL
    value: http://localhost:28080
  - name: PROVIDER_URL
    value: http://localhost:18080
  - name: contract-agreement-id
    value: bb80c2cd-ec59-4c7e-ba34-366f6d92c564
  - name: pull-transfer-id
    value: "{{ENTER_VALUE_HERE}}"
  - name: transfer-endpoint
    value: "{{ENTER_VALUE_HERE}}"
  - name: transfer-auth-type
    value: "{{ENTER_VALUE_HERE}}"
  - name: transfer-auth-authorization
    value: "{{ENTER_VALUE_HERE}}"
  - name: CONSUMER_BACKEND_URL
    value: https://consback-edc-connector.apps.dcw1.paas.psnc.pl/edr-endpoint
  - name: PROVIDER_IDENTITY_HUB_URL
    value: "{{ENTER_VALUE_HERE}}"
  - name: CONSUMER_IDENTITY_HUB_URL
    value: "{{ENTER_VALUE_HERE}}"
  - name: FEDERATED_CATALOG_IDENTITY_HUB_URL
    value: "{{ENTER_VALUE_HERE}}"
  - name: DATA_SPACE_HUB_URL
    value: "{{ENTER_VALUE_HERE}}"
  - name: FEDERATED_CATALOG_URL
    value: http://localhost:9181
  - name: child_ids
    value: "{{ENTER_VALUE_HERE}}"
  - name: child_idx
    value: "{{ENTER_VALUE_HERE}}"
  - name: vc-to-delete
    value: "{{ENTER_VALUE_HERE}}"
  - name: CONSUMER_DID
    value: did:web:consumer-ih%3A7083:alice
  - name: CONSUMER_DSP_URL
    value: http://consumer-connector:8082/api/dsp
  - name: PROVIDER_DID
    value: did:web:provider-ih%3A7093:bob
  - name: PROVIDER_DSP_URL
    value: http://provider-connector:8192/api/dsp
  - name: PROVIDER_CONNECTOR_MANAGEMENT_URL
    value: http://localhost:19193/management
  - name: policy-id
    value: test-policy
  - name: asset-id
    value: test-asset
  - name: contract-definition-id
    value: cdef-test
  - name: FEDERATED_CATALOG_TARGETS_URL
    value: http://localhost:8296
